### ISSUE TITLE
noise artefacts when creating notch filters

### ISSUE THREAD

**Issue by nilsbecker** [calf-studio-gear/calf#1]
when using the 12 band eq for bass management, i noticed pronounced noise artefacts. these occur when placing high Q (20-40) notch filters at low frequencies around 50-150 Hz. the artefacts are easy to hear when playing single bass notes or a sine sweep over this range, and they sound like zipper noise or a piece of paper placed on the driver.

i would think the same occurs also on the 8-band and 5-band but have not tried.

**Comment by boomshop** [comment]
This happens only in the bass band on very high Q with our filter design. Other equalizers don't allow such high settings probably because of this effect. I decided to allow this kind of high Q settings because it works well on mid and higher frequencies and I don't think there's a need to narrow the users choices.

**Comment by nilsbecker** [comment]
ok, that's fine but people should be warned in that case, somewhere in the documentation. even better would be to find the unsafe region and show a danger sign or something like that; or directly restrict the Q in dependence on the frequency. i think it's fair to say that a fresh user will just go ahead and assume that all eq settings are similar in sound quality result...

**Comment by boomshop** [comment]
A warning sign would not be sufficient in my experience because it heavily depends on the kind of material one produces. But a note in the manual is a good way to go I think. Thanks for the hint.

**Comment by nilsbecker** [comment]
ok. actually my story at the time was this: i needed a bass notch filter against room modes, and searched for eq plugins that would do that specifically. calf came up as one of the few that let me do it. so by allowing these settings, in a way you are attracting specifically the people that need that.

anyway, an easy-to-find note in the manual would be good
