### ISSUE TITLE
build problem with current master

### ISSUE THREAD

**Issue by ycollet** [calf-studio-gear/calf#10]
Hello,

I compile the current master branch on fedora 21 64 bits.
I've got an error message while building calf:

g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I.  -ffast-math -finline-limit=80   -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16   -I/usr/include/lash-1.0 -I/usr/include/alsa  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -msse -mfpmath=sse -MT session_mgr.o -MD -MP -MF .deps/session_mgr.Tpo -c -o session_mgr.o session_mgr.cpp
In file included from session_mgr.cpp:26:0:
./calf/utils.h:197:6: erreur: ‘vector’ in namespace ‘std’ does not name a template type
 std::vector <direntry> list_directory(const std::string &path);
      ^
Makefile:700: recipe for target 'session_mgr.o' failed
make[3]: *** [session_mgr.o] Error 1
make[3]: Leaving directory '/home/collette/repositories/LV2/calf/src'                                                                                                   
Makefile:733: recipe for target 'all-recursive' failed                                                                                                                  
make[2]: *** [all-recursive] Error 1                                                                                                                                    
make[2]: Leaving directory '/home/collette/repositories/LV2/calf/src'                                                                                                   
Makefile:585: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/collette/repositories/LV2/calf'
Makefile:386: recipe for target 'all' failed
make: *** [all] Error 2

A missing header perhaps ...

**Comment by boomshop** [comment]
Hey ycollet,

please pull once more.

**Comment by ycollet** [comment]
Thanks, it works now.

YC
