### ISSUE TITLE
0.0.60.1 Maintenance release?

### ISSUE THREAD

**Issue by pmjdebruijn** [calf-studio-gear/calf#102]
I noticed a lot of effort went into git master, including a lot of a bug fixes. Presuming a new major release isn't imminent, it would be rather nice to have a maintenance release of 0.0.60 with some of the accumulated bug fixes. I briefly skimmed the git log, where I found these potential candidates:

f57ab5f45bf556019673f3aa0b65416f1d549187
a7f9fb6b6fdf0621ec39769f19fa360e8bb37676
5ea453d27a61a29172e53fa837dfb67d28a91d3c
9c4abb5455df4d543b82b16d9f629dcf334f5423
d72df1da0e0062bdb8d676fd67723f274414f720
52ecdb4be0177f028412b2f466b19f22cfd2212d
f1f85c08e28dc95c07678553d363a8f38d684ab9
911a4734254b691c9e19d21062297b5c5fec908c ?
931559f20ca89ee4d2ea7f3c4127aace41d9bd98 ?
1b15f6e44b288162238a94d6b6d8bc297e7c3314 ?
fe184eb4e8eaa95746abd185a846c7a1acbb95ba ?
c115927a1ae2b0278244ba8840cff9fc3a19ee68
9bff7b62762bc5dbdc66136ccf717e647e982632
9a763ba6598c3505c2ffd309496fe80ef86c25ac ?
5b91b0fda17ff9d09075d3d1b1409eb618fa6dd9 ?
1b9e7c3900af947776ee5564376555baf3327ccb ?
d13b15233893e3441caa73126e9cfd808285c76e
851af01428a2b24d72cc977984566be771a941ce
3b86a70f0b7ab2a476778a6e23a0c7f07419cac4 ?
07c5ee90657e380c53383d9e4f1b9d46c2585751
f444d58eeeef3afe451f19fb4da9236217953b24
b73bce31d7668e033caeaddf21a018760c93a56f
413bd430479b04f93e06a341dff571ff459a114a
9bd7d2c588cbb24908e981b5d0cb55ec1c729d37

**Comment by pmjdebruijn** [comment]
Oh of course the relevant subset of https://github.com/calf-studio-gear/calf/pull/101

**Comment by pmjdebruijn** [comment]
At least this set applies cleanly to the 0.0.60 codebase:
413bd430479b04f93e06a341dff571ff459a114a
52ecdb4be0177f028412b2f466b19f22cfd2212d
851af01428a2b24d72cc977984566be771a941ce
9c4abb5455df4d543b82b16d9f629dcf334f5423
b73bce31d7668e033caeaddf21a018760c93a56f
c115927a1ae2b0278244ba8840cff9fc3a19ee68
d72df1da0e0062bdb8d676fd67723f274414f720
f57ab5f45bf556019673f3aa0b65416f1d549187

**Comment by trebmuh** [comment]
+1 I agree that a new release version including work around the issue with older compilers would be awesome.

**Comment by W-Floyd** [comment]
I second this. Looking to add this to the Solus repo, master builds fine, but last release does not.

**Comment by boomshop** [comment]
We're still fixing some important bugs while working towards a new release.

**Comment by pmjdebruijn** [comment]
I understand that a new major release might not be imminently feasible.

But the 0.0.60 release is fairly old now, and doesn't compile new recent compilers, forcing distro packagers to cherry pick patch themselves, until there is a new release.

Offering a new patch release (for example 0.0.60.1) would allow distro packagers to stick with using a tested official source tarball, reducing the chance of regressions in the distros.

Even if a 0.0.60.1 release doesn't fix all known issues, it will very likely still be much better than 0.0.60, which in my opinion would make it worthwhile, even if it's just a stop-gap until you can do a new major release. And it would take some of the pressure off making that new major release.

So taking 0.0.60 and applying the following commits,

These commits seem critical for a new patch release:
https://github.com/calf-studio-gear/calf/commit/784c8428c885bc420291de63e0dd7e2839e682bd
https://github.com/calf-studio-gear/calf/commit/f392c599fc35e6fda456b0e7bed020521fb711fc

Parts of this would be nice:
https://github.com/calf-studio-gear/calf/commit/6eb51adb9db0f915ed80f072513681ad3205357e 

And patches mentioned here might be worth considering as well:
https://github.com/calf-studio-gear/calf/issues/102#issuecomment-264286649

**Comment by falkTX** [comment]
for me personally, I'd rather see all efforts focused on a stable 'next' release, rather than fixing the old one.
there are things you can cherry pick, but not everything.

a middle ground could be to release a beta version for public testing.
