### ISSUE TITLE
Allow higher Q for Vocoder filters

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#104]
My experience with Calf Vocoder is that it's really great if you're doing classical voice + synth vocoding.
It gives a very pleasing, smooth sound. Recently I was trying to use it more creatively to mess up some synthesized sounds and I realized the filter banks are pretty wide, even in their most narrow setting.

I know that this prevents "holes" in the spectrum to apprear, but sometimes I'd want to have these holes!

I'd like much higher Q values to be allowed - the "High Q mode" doesn't seem to make any change for me - I thought it's going to multiply the Q values by 4 but it didn't happen.

**Comment by boomshop** [comment]
Oh and please let us hear your results! .)

**Comment by unfa** [comment]
I can't wait to test it and deliver audio :D
