### ISSUE TITLE
In LMMS gui of calf plgins not showing ? 

### ISSUE THREAD

**Issue by Gps2010** [calf-studio-gear/calf#11]
I am on openSUSE 13.1 64 bit. Becaue of an topic on the lmms forums, I found out, I should have those great looking guis in lmms too, but I don't.

I hope this is the right place to ask for help.

LMMS comes with calf plugins, they only have a boring gui, (only knobs) but do work.

I have lmms installed and calf, but I am lost on what to do next ? 

First question does calf work with pulseaudio too ? 
Second question, how do I proceed  ?

**Comment by boomshop** [comment]
> LMMS comes with calf plugins, they only have a boring gui, (only knobs) but do work.

LMMS isn't capable of LV2 but only of LADSPA or VST. The calf plug-ins delivered with LMMS are outdated and not supported anymore since we dropped LADSPA support.

> First question does calf work with pulseaudio too ? 

No, you need Jack for calf*jack*host or a LV2 host like Ardour.

**Comment by Gps2010** [comment]
Thank you.
