### ISSUE TITLE
Can't make: benchmark?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#110]
I downloaded the latest Git code today and I'm trying to build Calf plugins for the first time. I've got to a point where I don't know what to do though.

After a little while of "make" doing it's thing it stopped, and I got this:

```
benchmark.o:(.rodata._ZTVN12calf_plugins19filter_audio_moduleE[_ZTVN12calf_plugins19filter_audio_moduleE]+0x2f0): undefined reference to `calf_plugins::frequency_response_line_graph::get_gridline(int, int, int, float&, bool&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, calf_plugins::cairo_iface*) const'
benchmark.o:(.rodata._ZTVN12calf_plugins19filter_audio_moduleE[_ZTVN12calf_plugins19filter_audio_moduleE]+0x2f8): undefined reference to `calf_plugins::frequency_response_line_graph::get_layers(int, int, unsigned int&) const'
benchmark.o:(.rodata._ZTVN12calf_plugins19filter_audio_moduleE[_ZTVN12calf_plugins19filter_audio_moduleE]+0x300): undefined reference to `calf_plugins::frequency_response_line_graph::get_crosshair_label[abi:cxx11](int, int, int, int, float, int, int, int, int) const'
collect2: error: ld returned 1 exit status
Makefile:657: recipe for target 'calfbenchmark' failed
make[3]: *** [calfbenchmark] Error 1
make[3]: Leaving directory '/home/unfa/Downloads/calf-master/src'
Makefile:764: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/unfa/Downloads/calf-master/src'
Makefile:596: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/unfa/Downloads/calf-master'
Makefile:398: recipe for target 'all' failed
make: *** [all] Error 2
```
After this I tried doing "make install" to see it maybe there's at least something done and ready for use.
The error message repeated itself - here's the full listing: http://pasteall.org/155574

What can I do about this to build Calf plugins?

**Comment by jrigg** [comment]
From the pastebin listing it looks like it's failing to find header files. Did you run ./autogen.sh first?

**Comment by unfa** [comment]
Yes, I've run ./autogen.sh - it semdd to finish fine and printed out the build configuration. Then I have run make and it didn't finish properly.

**Comment by trebmuh** [comment]
from the paste : `../libtool: line 2639: func__fatal_error: command not found` so do you have the "libtool" package installed on your system?

**Comment by boomshop** [comment]
No response for > 12 months so I'll close the issue. Feel free to re-open if the problem still exists and you made sure that libtool is installed.
