### ISSUE TITLE
Vocoder snaps back to 8 bands when opening the GUI

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#112]
When using Calf Vocoder in Ardour - I've noticed that when I set the band number to anything else than 8 (the lowest), it'll snap back to the 8-band if I close and open again the GUI. Right when I open the GUI again I can hear a loud click, and the Vocoder changes it's settings to use 8 bands.

I don't know if this is present still in the latest code.

**Comment by boomshop** [comment]
c9e8418 was meant to fix this issue but it seems to only work in calfjackhost, not in Ardour.

**Comment by boomshop** [comment]
Fixed in latest git.
