### ISSUE TITLE
Feature Request: Reverse Envelope Filter

### ISSUE THREAD

**Issue by ReubenM** [calf-studio-gear/calf#12]
Just want to be able to set the envelope to drive the filter frequency down rather than up...

**Comment by boomshop** [comment]
Just switch the position of upper and lower frequency.

**Comment by ReubenM** [comment]
*facepalm* It never even occurred to me that might be possible. Thanks.

**Comment by boomshop** [comment]
I added a hint to the manuals now, thanks for pointing it out.
