### ISSUE TITLE
Git binary release?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#120]
I'd love to get a recent build to test out some new features (possibly make some videos about them), but I can't build it myself. Could there be a binary release?

**Comment by trebmuh** [comment]
@unfa : what distribution are you using ?

**Comment by unfa** [comment]
Linux Mint with KX Studio repositories.

**Comment by boomshop** [comment]
There's a walk-through kind of explanation how to do it on debian-based systems on our website - doesn't this work for you?

http://calf-studio-gear.org/#install

**Comment by trebmuh** [comment]
@unfa : then you can ask kxstudio's team (falktx) to update the package maybe?

**Comment by falkTX** [comment]
Install calf-plugins-git package and you should be good to go.

**Comment by unfa** [comment]
Yep, the calf-plugins-git KX Studio package is the easier way to test out new features.
I tried building but failed with this result: #110
