### ISSUE TITLE
no bypass on reverb effects?

### ISSUE THREAD

**Issue by edge226** [calf-studio-gear/calf#122]
Okay so every plugin I've played around with has a bypass button except reverb, It seems to be the only plugin where I probably don't want it on all the time but it would be cool to be able to turn on during certain times.

Without the bypass the reverb feature seems unusable to me.

**Comment by trebmuh** [comment]
Don't you have this button ?
![calf-reverb](https://cloud.githubusercontent.com/assets/8705846/22354796/481ff658-e427-11e6-8934-b1cc89d942c0.png)

**Comment by boomshop** [comment]
You can't bypass a reverb since the effect is added to the dry signal. That's the reason why there's the "active" switch.

**Comment by edge226** [comment]
I don't have the Active switch, I have this.
![calf - reverb_198](https://cloud.githubusercontent.com/assets/4232080/23339391/5fdc0542-fbde-11e6-9d67-d4116e93a347.png)
