### ISSUE TITLE
disable autoconnections

### ISSUE THREAD

**Issue by edge226** [calf-studio-gear/calf#123]
I tinkered with using jalv last night. Everything worked well but it was fractured into pieces and saving settings was difficult.

Calf does a better job at doing the latter two things however every time I connect *anything* to pulse it decides its a good idea to connect everything together wrong.

Can we get a way to remove the annoying autoconnection stuff that is causing me a headache and to swear far more than needed for this task.

Usually having a wide array of software to play around with is absolutely fantastic however not in the case of Calf, It has actually been a negative because of this bug.

I wonder what this plugin does? Oh it connects everything together and completely screws my audio, Might as well disconnect *everything* and reconnect *everything* due to it now being so messed up its not even funny.

![selection_183](https://cloud.githubusercontent.com/assets/4232080/22355034/7822a6ee-e3e5-11e6-84c6-7251c92da562.png)
![selection_184](https://cloud.githubusercontent.com/assets/4232080/22355035/782422e4-e3e5-11e6-90a7-e150650f55a1.png)

So the more things I work with in Calf the more it tries to automatically decide for me and screws up all the connections that I've worked on, The more work Calf creates for me.

Launching the plugins through Jalv resolves the issue, I no longer get the horribleness that is shown in the second screenshot. But I also lose the benefits of using Calf, Which negates the usefulness of it.

**Comment by boomshop** [comment]
As long as you don't start Calf  with one or more plugs surrounded by "!" via command line it doesn't connect anything automatically. Probably an issue with your jack host?

BTW you're using a quite outdated version.

**Comment by edge226** [comment]
Thanks for the info. Was using the version manjaro has in their repo. I'll check the git version.
