### ISSUE TITLE
Limit control value text after floating point

### ISSUE THREAD

**Issue by AS383** [calf-studio-gear/calf#128]
In some cases control values have long text after floating point. This is not readable. Limit to one or two will be nice.

**Comment by boomshop** [comment]
Is this still an issue with 0.90.0? And if so please point me to (at least some of) the affected parameters.

**Comment by trebmuh** [comment]
@AS383 ping ^

**Comment by AS383** [comment]
Tested version 0.90.1.
Now it's Ok :) Thanks!
