### ISSUE TITLE
Changed names of the parms in Vintage Delay

### ISSUE THREAD

**Issue by suedwestlicht** [calf-studio-gear/calf#131]
After installing CALF plugins from git head I noticed that Vintage Delay's parms were not completely restored when loading an existing song in my DAW (Qtractor).

"Amount" and "Dry Amount" have changed to "Wet" and "Dry"

I'd suggest keeping the old parm names to make upgrades hassle-free for long time CALF users.

**Comment by boomshop** [comment]
Yes, one major update broke backwards compatibility due to maintainable reasons. We'll try to prevent in future versions but we can't roll this one back cause it would break things _again_ for other users.
