### ISSUE TITLE
Delete old ladspa and dssi files when installing

### ISSUE THREAD

**Issue by falkTX** [calf-studio-gear/calf#135]
If a user has calf from packages, it handles the removal of old files for the user.
But for manual install the old ladspa and dssi plugins will remain.
I recommend adding a rm -f $(DESTDIR)$(PREFIX)/lib/ladspa/calf.so or similar to calf's make install target.
This will resolve issues like #134

**Comment by boomshop** [comment]
Hey Filipe, thanks a lot for the input. Shouldn't this be added to make uninstall?

**Comment by falkTX** [comment]
It seems a better fit yes, but how many users will actually run that?

**Comment by boomshop** [comment]
True. BTW do you want to have access to this git? Could probably make things easier.

**Comment by falkTX** [comment]
sure, but since I don't know autotools at all, I'm not that much help here.

**Comment by boomshop** [comment]
Yep, np, will add it on my own. Nonetheless I added you to the contributors list.

**Comment by kfoltman** [comment]
I've added a configure check for old LADSPA plugins and rogue versions installed in wrong directories. Could you guys check if it's working properly for you? I'm not good at autohell and I don't want to break things too badly before the release.

**Comment by boomshop** [comment]
I was able to test it today:

* removed every installed file related to calf
* installed 0.0.19 (with ladspa and dssi)
* tried to make, resulting in two errors: first about already installed ladspa, second about already installed lv2

So it works, thanks! Two suggestions: check all possible installed files at once, add dssi to the check, too.

**Comment by kfoltman** [comment]
If I recall it correctly DSSI is just an extra functionality in the LADSPA plugin + extra executable, so it should be covered. Not sure what you mean by checking all possible installed files at once - theoretically, the calf.so is the worst offender so to speak, but maybe other Calf dynamic libraries can cause harm, too.

**Comment by boomshop** [comment]
> Not sure what you mean by checking all possible installed files at once

Every execution of make threw an error (first ladspa, second lv2), the idea was to check both files in the same run.

**Comment by kfoltman** [comment]
Ah - well, I think two different errors at the same time might confuse some users - I think in all typical situations configure quits on the first error.

**Comment by boomshop** [comment]
Reasonable.
