### ISSUE TITLE
Hide calfjackhost to system tray

### ISSUE THREAD

**Issue by UltraCoderRU** [calf-studio-gear/calf#137]
Hello.
It would be nice to have ability to hide calfjackhost window to system tray. For example, I use calf plugins to to process Pulseaudio streams and forced to use alltray to hide calfjackhost window. Even better, there can be a switch in tray icon menu to enable/disable all plugins currently in host.
Best regards,
Kirill.

**Comment by v-fox** [comment]
And I just put it on a separate desktop via kwin/openbox rules.

Also, its knob-style GUI, while fancy, is quite impractical and doesn't scale well. Many windows with inconsistent sizes are difficult to juggle around, colours are non-optimal, knobs are imprecise and re-opening and moving windows on every session load is annoying. And yet there is nothing better. So, maybe rethinking the entire style might be in order, so it would be more compact, illustrative and permissive for quick-switching... after there is a new release and something is done for it to use more than 1 core.

**Comment by trebmuh** [comment]
Adding my voice to @UltraCoderRU 's suggestion, it'd be neat and awesome to have calfjackhost in the systray (like jalv.select does as an example).

**Comment by v-fox** [comment]
Great job, thanks.

But is there a way to hide it by default or at least if it's launched with '--state' option ? That doesn't seem to be forcible via WM rule, unfortunately.

**Comment by trebmuh** [comment]
Nice job @boomshop , thanks!

+1 with @UltraCoderRU a global bypass as an option in the systray icon would be awesome.

**Comment by boomshop** [comment]
@v-fox this was added yesterday.
@trebmuh since there's no global bypass and some plugins have bypass, others have on/off switch and some doesn't have any of those the behavior wouldn't be consistent. Additionally it could lead to damage of amps/speakers/headphones/ears if used accidentially.

**Comment by trebmuh** [comment]
ack

**Comment by v-fox** [comment]
> @v-fox this was added yesterday.

Thanks. But, unfortunately, it seems to be bugged: for me the window is rendered completely empty if it starts with this option enabled, can't even get to options to disable it, have to edit config manually.

**Comment by trebmuh** [comment]
Works for me here. @v-fox what system are you using? and what windows manager?

**Comment by boomshop** [comment]
Please test the latest git.

**Comment by v-fox** [comment]
> Works for me here. @v-fox what system are you using? and what windows manager?

openSUSE "Tumbleweed" rolling with kwin5

> Please test the latest git.

Yep, that worked. The window opens up for a second on start and then disappears but looks fine now.
