### ISSUE TITLE
Plugin category?

### ISSUE THREAD

**Issue by Narann** [calf-studio-gear/calf#14]
Hi team and thanks for the hard work! :)

It's maybe not the place to talk about this but as I don't know how to ask I will try here.

Calf plugins doesn't seems to have any category assigned:

![calf_categories](https://cloud.githubusercontent.com/assets/659708/8342992/f50db30e-1a9e-11e5-8405-f52a1e56b0be.png)

This mean they appear in "plugin" category:

![calf_categories_001](https://cloud.githubusercontent.com/assets/659708/8343043/5b45c242-1a9f-11e5-85df-e363c656c23a.png)

Maybe I'm wrong but I suspect the category in set inside the LV2 spec.

Feel free to close this ticket if it's not related to your work but if so, I would really love to know where I should report this.

Keep the good work! Those plugins are awesome!

**Comment by boomshop** [comment]
Hey Narann,

unfortunately I'm not able to reproduce it with any version of Ardour (2, 3, 4).

**Comment by Narann** [comment]
You mean plugins are properly category organized?

Any idea where it could come from? Compilation? Old version? Feel free to close this ticket if everything work on your side.

**Comment by boomshop** [comment]
I pushed a possible bug fix to the repository. Please build Calf from GIT as described on the website http://calf-studio-gear.org and test if the problem still persists. Ask if you need help.

**Comment by Narann** [comment]
Great! Only few of them are still in Plugin:

![calf_categories_002](https://cloud.githubusercontent.com/assets/659708/8345597/63bac57e-1abf-11e5-9a37-7d26dbab067a.png)

Maybe those are hard to organize or don't have a particular category. But I guess _Equalizer_ could be in _EQ_.

Anyway, look like the big part of the job is done

**Comment by boomshop** [comment]
Please try to do
`make uninstall`
`make distclean`
`./autogen.sh`
before you build and install.

**Comment by Narann** [comment]
It works! Thanks a lot!

Keep the good work! :)
