### ISSUE TITLE
calf-studio-gear.org has old and broken links

### ISSUE THREAD

**Issue by falkTX** [calf-studio-gear/calf#140]
Didn't know where else to report, but the calf website http://calf-studio-gear.org/ has some links that should be fixed.
I noticed in the recommendations, AVLinux link is broken and kxstudio one points to the old URL (at sourceforge)
AVLinux should point to http://www.bandshed.net/avlinux/
KXStudio should point to http://kxstudio.linuxaudio.org/
(also KXStudio should have 'KXS' in uppercase)

**Comment by boomshop** [comment]
Thanks a lot for pointing it out!

**Comment by falkTX** [comment]
Thanks for the quick update!
