### ISSUE TITLE
plugin URI changed, why?

### ISSUE THREAD

**Issue by rlrosa** [calf-studio-gear/calf#141]
Hi, why did the plugin URI changed?

I use ardour, they helped me work around this. My system hadn't been update un a couple of months. I imported a session created by a friend a couple of days ago and plugins failed to load because they weren't found, URI mismatch.
New version seems to be:

    http://calf.sourceforge.net/plugins/Equalizer5Band
    http://calf.sourceforge.net/plugins/Equalizer8Band

old version was:

    http://calf.sourceforge.net/plugins/eq5
    http://calf.sourceforge.net/plugins/eq8

Why was this changed?

**Comment by falkTX** [comment]
the URI did not change. those "old" ones were from kxstudio days of having ladspa versions, I did a change that messed up the URIs for LV2s.
I keep those old URIs in the kxstudio builds for compatibility reasons.
the plugins actually export the normal URI and the old one, with the normal having a lv2:replaces rule for the old one - so in theory the hosts should only use the correct URI. (sadly most hosts just ignore this rule)

so now you can manually fix up the URI on the ardour session file, or rebuild calf with a patch applied.
Patch here http://kxstudio.linuxaudio.org/Paste/raw/5jxRv.

this is not a calf issue, but a kxstudio one.
