### ISSUE TITLE
Some plugins crash ardour, some show no gui

### ISSUE THREAD

**Issue by spectromas** [calf-studio-gear/calf#15]
Not sure what is going on here, I'm sure this used to work. If I load calf compressor in ardour 4 and then try to open the gui of the plugin, ardour crashes and disappears. It seems that not all plugins will crash, if I try to load the Emphasis plugin I just get the ardour plugin header strip and no calf gui at all. 

I tried to open them in Carla and was successful. However, running the Carla vst host in Renoise and trying to open the gui also crashes the host. Fortunately in Carla there is an option for "Use UI bridges" and this fixes the crashes in Renoise but it would seem that the cause is the same as that of the problem in ardour. 

I am using the 0.0.60 release. I have also replicated this with the official ardour download as well, although this is particular log is with my own version: 

    ardour4
    bind txt domain [gtk2_ardour4] to /usr/share/ardour4/locale
    Ardour4.0.gentoo (built using 4.0-gentoo and GCC version 4.9.2)
    ardour: [INFO]: Your system is configured to limit Ardour to only 64000 open files
    ardour: [INFO]: Loading system configuration file /etc/ardour4/system_config
    Loading user configuration file /home/alex/.config/ardour4/config
    No H/W specific optimizations in use
    ardour: [INFO]: Loading default ui configuration file /etc/ardour4/default_ui_config
    ardour: [INFO]: Loading user ui configuration file /home/alex/.config/ardour4/ui_config
    ardour: [INFO]: Loading color file /etc/ardour4/dark.colors
    ardour: [INFO]: Loading ui configuration file /etc/ardour4/clearlooks.rc
    ardour: [INFO]: Loading ui configuration file /etc/ardour4/clearlooks.rc
    EngineControl::set_state
    setting input device to:  setting output device to:  Found nothing along /home/alex/.config/ardour4/templates:/usr/share/ardour4/templates
    run dialog
    Announcement is: Version 4.1 has been released. Update at http://ardour.org/download
    Scanning folders for bundled LV2s: /usr/lib64/ardour4/LV2
    error: failed to expand CURIE `fomp:'
    error: attempt to add quad with NULL field
    error: failed to expand CURIE `pprops:hasStrictBounds'
    error: attempt to add quad with NULL field
    error: failed to expand CURIE `pprops:hasStrictBounds'
    error: attempt to add quad with NULL field
    error: failed to expand CURIE `pprops:hasStrictBounds'
    error: attempt to add quad with NULL field
    error: failed to expand CURIE `pprops:hasStrictBounds'
    error: attempt to add quad with NULL field
    Set cursor set to default
    CALF DEBUG: instance 0x357c320 data 0x8067d58
    CALF DEBUG: calf 0x7fc7f9b347f0 cpi 0x7fc7f916c2a0
    
    ** (ardour-4.0.gentoo:7472): ERROR **: Unknown parameter mix
    [1]    7472 trace trap  ardour4

This was opening an empty project, loading calf compressor and trying to open the gui. 

If there is any more information I can provide in order to troubleshoot this the please let me know, I am keen to get to the bottom of it but not sure where to begin really. If a gdb output from ardour would helpful then I can provide that.

**Comment by boomshop** [comment]
It seems there are some inconsistencies in your installations. The mix port was introduced in c884449fa1c35512e1f63f1726c0d2a974ce45aa (Sun Nov 3 22:46:12 2013 +0100). Try to remove every installation of Calf (e.g. do you have one in /usr/local and one in /usr?) and reinstall it. Another thought - are there any Ardour versions shipping Calf plug-ins for your distribution?

**Comment by spectromas** [comment]
Thank you, I think I found the cause of the problem. I uninstalled the calf package and searched for anything else in the system for calf and did find a ladspa file I had been keeping around from a kxstudio package, moved that elsewhere and then built from git source, plugins ran fine (I like the new gui by the way!). I uninstalled that and reinstalled the regular stable package and I'm not having any problems in ardour now. Many thanks!

Running the calf plugins in carla without the "Use UI bridges" option enabled still causes carla and the host to segfault though but from what I have heard this is a semi-known issue. Is it worth opening a bug report for that?

**Comment by boomshop** [comment]
Good to hear that! Do you have any link to a discussion about the Carla issue - at best with FalkTX involved?

**Comment by spectromas** [comment]
I did open a report on carla's page about it https://github.com/falkTX/Carla/issues/242 
It does work as falkTX suggests there but if a fix can be made somewhere it would be of course be a better solution.

**Comment by boomshop** [comment]
Thanks for the link, we're discussing it.
