### ISSUE TITLE
Right channel does not connected automatically by Ardour 5.12 on mono strips

### ISSUE THREAD

**Issue by AS383** [calf-studio-gear/calf#151]
On [0.9.0](https://github.com/calf-studio-gear/calf/releases/tag/0.90.0) to LV2 version was added midi port. It cause an error: right channel does not connected automatically by Ardour **5.12** on mono strips with strict IO disabled. It can be fixed manually by editing plugin pinout.
![calf_0 9_ardour_5 12_r_channel_not_connected](https://user-images.githubusercontent.com/19341856/32533102-36e3fd22-c481-11e7-9d02-4a36dce0fca2.png)
If there are the way to disable a midi port, please tell.

**Comment by IvanDSM** [comment]
Is this really a Calf bug? From what I've seen, this is normal Ardour
behavior with stereo plugins on a mono track. Might be more appropriate
to add a feature request on Ardour's issue tracker for doing mixdown on
stereo plugins in mono tracks.

Em qua, 2017-11-08 às 05:44 +0000, Anton Stankevich escreveu:

**Comment by AS383** [comment]
@IvanDSM, OK, I report it to Ardour's bug tracker too: http://tracker.ardour.org/view.php?id=7503

**Comment by lucianodato** [comment]
This seems to be the right behavior. Generally you do want that a mono channel stays as a mono channel, otherwise you should be using a stereo channel with duplicated region or outputs. I don't think this is a bug.

**Comment by boomshop** [comment]
This is Ardour related, so closing this issue. If you still think it's a Calf bug feel free to re-open.
