### ISSUE TITLE
Should calf require C++11?

### ISSUE THREAD

**Issue by JohannesLorenz** [calf-studio-gear/calf#157]
With g++ 5.4.0, I get warnings about code that requires C++11. It should either be set in the Makefiles (which will force everyone to use a C++11 compiler), or to rewrite such constructs to be C++03 compatible. What is preferred?

```
./calf/modules_dist.h:131:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     const float freq_min = 600.f;
                            ^
./calf/modules_dist.h:132:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     const float freq_max = 1800.f;
                            ^
modules_dist.cpp: In member function 'virtual void calf_plugins::vinyl_audio_module::post_instantiate(uint32_t)':
modules_dist.cpp:808:51: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
     std::string* paths = new std::string[_synths] {

./calf/modules_dist.h:131:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     const float freq_min = 600.f;
                            ^
./calf/modules_dist.h:132:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     const float freq_max = 1800.f;
```

**Comment by JohannesLorenz** [comment]
Btw, using clang-5.0, calf does not compile without specifying `CXXFLAGS=-std=c++11`:

```
modules_dist.cpp:808:50: error: expected ';' at end of declaration
    std::string* paths = new std::string[_synths] {
```

**Comment by tresf** [comment]
Seems to affect some older gcc versions as well... here's `gcc 4.9.4` from a cross-compiler that we use... (apologies for the strange naming convention, we're forked and build with CMake, so this bug does not affect us downstream, just offering this for informational purposes).

```
In file included from /opt/mingw32/i686-w64-mingw32/include/c++/4.9.4/cstdint:35:0,
                 from /home/travis/build/LMMS/lmms/plugins/LadspaEffect/calf/veal/src/utils.cpp:27:
/opt/mingw32/i686-w64-mingw32/include/c++/4.9.4/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
```

**Comment by falkTX** [comment]
from what I understood, only a few things added somewhat recently to calf require c++11, the old code did not and gtk2 and its dependencies do not as well.
so instead of requiring c++11, a wiser option is to replace the c++11 specific code with c++98 compatible variants.

**Comment by JohannesLorenz** [comment]
That code is indeed newer, but C++11 is usually considered an improvement to C++98, and it's established for 7 years already. Zyn and LMMS (who have a large user base) switched years ago. I don't know of any stable linux (even LTS versions) that don't support C++11 yet. Practically, the number of users who can not use C++11 could be estimated as 0.

It's compatibility vs code quality. Such a design decision must be made by the CALF authors.
