### ISSUE TITLE
out of bounds values on some lv2 control ports

### ISSUE THREAD

**Issue by falkTX** [calf-studio-gear/calf#16]
my little validation script caught 2 small errors in the Vocoder plugin.
port 'Carrier' and port 'Modulator' default value are out of bounds.

the modulator port has this info:
>        lv2:default 0 ;
>        lv2:minimum 1.58490e-05 ;
>        lv2:maximum 16 ;

1.58490e-05 > 0, so the default should be 1.58490e-05 instead.
The 'carrier' port has the exact same issue.

**Comment by boomshop** [comment]
Thanks for pointing it out, fixed in c607ad60b5499c7cd89541598212c6855d953bd4
