### ISSUE TITLE
Turn off makeup gain on limiter?

### ISSUE THREAD

**Issue by echoplex-media** [calf-studio-gear/calf#162]
I would love to have the option to turn off the makeup gain on the limiter.  I know I can achieve much the same thing with a compressor, but it would be very cool to be able to turn it off on the limiter.

**Comment by boomshop** [comment]
The Limiter routine is completely different from a compressor.

Regarding your request: the `limit` knob limits the signal at the given gain and adds the same amount back to the signal. In compressor terminology: threshold and makeup are combined on this knob cause that's the average way of using this device in a master strip. If you want a different output level you could use the `Out` knob on top.

Did I get you right?

**Comment by echoplex-media** [comment]
That's our current method, but it kills some of the dynamics.  If I could set it up to just duck anything over, say, -6db, without adding makeup gain, it would help us maintain some of the dynamic range of the music we play.

**Comment by boomshop** [comment]
Then just turn down `out` level to -6dB, too. It's a parameter already available and not that much more user interaction than switching the auto makeup to off. Result is exactly the same.
