### ISSUE TITLE
Does Monosynth modulation matrix work?

### ISSUE THREAD

**Issue by DJTECKING** [calf-studio-gear/calf#168]
I can't make modulation matrix work in monosynth.
I certainly do something wrong.
How is this supposed to work, does it really work?

**Comment by boomshop** [comment]
Modulation Matrix works well. To test:

- Start jackd
- Start calffjackhost and add the Monosynth
- Start jack-keyboard and connect its output to Monosynth MIDI in
- Set Source=Velocity, Amount=100, Destination=Resonance on the first entry in ModMatrix
- Switch back to Audio Path
- Klick some keys on the keyboard, change Velocity fader on keyboard, klick notes again and watch how the resonance in the filter display changes

**Comment by DJTECKING** [comment]
Starting Monosynth without touching any param?
I told about [this](https://calf-studio-gear.org/images/plugins/Calf%20-%20Monosynth%20-%20Modulation%20Matrix.jpg) screen, I think I was not really explicit.

I want, for example, modulate Osc1<>2 mix by envelope 1.
I saw all things working really well but this last screen.

**Comment by boomshop** [comment]
Did you try the example exactly as stated above?

**Comment by DJTECKING** [comment]
No, I didn't try exactly this, I use calf pluggins through LV2 in ardour5. I'll try tonight monosynth standalone.
I've been using modulation in the first "Audio Path" and "Modulation" tabs and seen this working perfectly.
I wanted to be sure we're not talking about these two tabs but the third one : "Modulation Matrix".
I want to map Envelope on something else than filters or gain... I thought "Modulation Matrix" was made for this but I can't have things working the way I expect.
(Expected in correlation of what I chose in the array of the tab "Modulation Matrix").

Hoooo, just understand, the amount thing is the problem. I'll try thing with amount. I suppose that amount is a percentage...

**Comment by boomshop** [comment]
Your expectations are right, Modulation Matrix is meant to map different MIDI parameters onto other aspects of the synth. And yes, you need to adjust the amount. But I don't really know what kind of value this is, might be percentage but I'm not sure (since I didn't develop this synth). Probably Krzystof has something to add.

**Comment by DJTECKING** [comment]
Ok, now in front of Ardour and Calf. Seen that modulation is working and it gives great results.
Problems comes from Ardour when we want to change amount : Ardour does not release focus and stops field editing when typing some num keys. That is not Calf relevant.
I now wait for Krzystof explanations on amount units and  Source -> Mapping -> Modulator equation because it is not totally self explicating... Thanks a lot.

**Comment by boomshop** [comment]
Good to hear you made it work. I fear that Krzysztof isn't stopping by too often so probably you should try to send a mail or something.
