### ISSUE TITLE
Sidechaining leveling is inactive if sidechain input is not used

### ISSUE THREAD

**Issue by JohannesLorenz** [calf-studio-gear/calf#175]
IIRC, if the parameter "sc route" is false, the sidechain signal is discarded, and the input sidechains itself:

```
    float leftAC  = inL;
    float rightAC = inR;
    float leftSC  = inL;
    float rightSC = inR;
    float leftMC  = inL;
    float rightMC = inR;

    if (*params[param_sc_route] > 0.5) {
        leftAC  = inL;
        rightAC = inR;
        leftSC  = in2L * *params[param_sc_level];
        rightSC = in2R * *params[param_sc_level];
        leftMC  = inL;
        rightMC = inR;
    }
```
Now, if the signal is sidechaining itself, it might still be desired to multiply `inL` and `inR` with `*params[param_sc_level]`. If the idea of "sc routing" set to false is that the input signal is also the sidechain signal, that sidechain signal should maybe also be multiplied with "sc level".

Background: LMMS can only handle 2 inputs, so many users "abuse" the "sc level" parameter for sidechaining: The sidechain signal feeds a peak controller, and the sc level is being connected to that controller. This worked with CALF 0.19, but fails with master (more exactly, since 83ce593bc579bb816440e304ebb116943d670db4 ).

Thanks to @karmux for [finding](https://github.com/LMMS/lmms/pull/3987#issuecomment-385253247).

**Comment by boomshop** [comment]
Thanks!
