### ISSUE TITLE
version 0.90.1 missing on github

### ISSUE THREAD

**Issue by trebmuh** [calf-studio-gear/calf#186]
I can see [here](http://mein-neues-blog.de/2018/07/08/calf-0-90-1-released/) and [here](https://github.com/calf-studio-gear/calf/blob/master/ChangeLog) that there is a 0.90.1 version, but there is nothing [here](https://github.com/calf-studio-gear/calf/releases).

**Comment by boomshop** [comment]
Fixed.

**Comment by trebmuh** [comment]
Awesome. Thanks for your quickness @boomshop .
