### ISSUE TITLE
calfjackhost and systray

### ISSUE THREAD

**Issue by YLB-YLB** [calf-studio-gear/calf#187]
Hi!
Lately I've been launching calfjackhost at system startup so I've a system-wide EQ and limiter sitting in the systray (with a nice icon :) ). It fulfils my needs perfectly and with time I found that I was missing two little things that could improve its usability. They are both borrowed from falkTX's Cadence that I use extensively in my setup.

The first one is a switch to launch calfjackhost minimized into the systray like you can with _cadence --minimized_

The second one is the possibility to not close calfjackhost while closing the window but sending it to systray instead.

Thanks a lot for the plugins anyway!

**Comment by boomshop** [comment]
Thanks for the idea.
