### ISSUE TITLE
Build failure with gcc4

### ISSUE THREAD

**Issue by falkTX** [calf-studio-gear/calf#192]
There are 2 issues here.

First, with the latest code, we need to manually specify c++11 mode in gcc.
It is the default since some gcc versions (not sure which one), but for gcc4 for sure it is not.
Adding `-std=gnu++11` to CXXFLAGS partially fixes the build.
I can't handle auto-hell, so I did not attempt to add it to the repo.

Second, a build failure in newly introduced code.
```
./calf/orfanidis_eq.h: In constructor ‘OrfanidisEq::EllipticTypeBPFilter::EllipticTypeBPFilter(size_t, OrfanidisEq::eq_double_t, OrfanidisEq::eq_double_t, OrfanidisEq::eq_double_t, OrfanidisEq::eq_double_t)’:
./calf/orfanidis_eq.h:1006:13: error: ‘std::complex_literals’ has not been declared
      j(std::complex_literals::operator""i(static_cast<long double>(1.0)))
```

The `std::complex_literals` is a C++14 feature, something that gcc4 (and I believe gcc5) do not provide.
It is quite the recent C++ feature.
I see it only used once in the entire codebase. Can we replace with something else please?

**Comment by falkTX** [comment]
hmm why wait, I am on the case, found an implementation of that function in the official documentation.
See https://en.cppreference.com/w/cpp/numeric/complex/operator%22%22i

Since I am not 100% certain it is correct, I will do a PR.

**Comment by falkTX** [comment]
hmm I forgot I can't push changes while at work :P
(multiple git user accounts)

Leaving a patch file here, please apply if you think it makes sense:
```
diff --git a/configure.ac b/configure.ac
index b9c3d50..82ca568 100644
--- a/configure.ac
+++ b/configure.ac
@@ -172,6 +172,9 @@ if test "$set_enable_sse" = "yes"; then
   CXXFLAGS="$CXXFLAGS -msse -mfpmath=sse"
 fi
 
+# We require C++11
+CXXFLAGS="$CXXFLAGS -std=gnu++11"
+
 ############################################################################################
 # Create automake conditional symbols
 AM_CONDITIONAL(USE_JACK, test "$JACK_ENABLED" = "yes")
diff --git a/src/calf/orfanidis_eq.h b/src/calf/orfanidis_eq.h
index c576694..de0332a 100644
--- a/src/calf/orfanidis_eq.h
+++ b/src/calf/orfanidis_eq.h
@@ -1003,7 +1003,7 @@ public:
 	EllipticTypeBPFilter(size_t N,
 	    eq_double_t w0, eq_double_t wb,
 	    eq_double_t G, eq_double_t Gb) :
-	    j(std::complex_literals::operator""i(static_cast<long double>(1.0)))
+	    j(std::complex<long double>{0.0L, 1.0L})
 	{
 		/* Case if G == 0 : allpass. */
 		if(G == 0) {
```

**Comment by boomshop** [comment]
Not sure if relying even on C++11 is a good idea. I'd like to ask @thedrgreenthumb if there's some other replacement for this?

**Comment by thedrgreenthumb** [comment]
Please, check the fresh pull request from my side.

**Comment by boomshop** [comment]
Thanks a lot! @falkTX could you please test against your build environment?

**Comment by falkTX** [comment]
sorry for the delay, confirmed fixed
