### ISSUE TITLE
Hide systray?

### ISSUE THREAD

**Issue by ZuluEchoRomeoOscar** [calf-studio-gear/calf#208]
Manjaro Stable with i3wm

I start calfjackhost at startup with
 `exec --no-startup-id            calfjackhost -l ~/calf_default`
and send it to the scratchpad for recall as a floating window whenever required. This makes the systray icon somewhat redundant in my case, and I'm wondering if there is any way to disable it?

**Comment by ZuluEchoRomeoOscar** [comment]
Thanks!

**Comment by boomshop** [comment]
You're welcome!
