### ISSUE TITLE
Knobs and graphs not drawing

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#21]
![calf no knobs](https://cloud.githubusercontent.com/assets/491704/8858665/fae75f28-3178-11e5-809b-48b67e59bea6.png)

I'm using KX Studio's repositories and package calf-plugins-git in version 2:0.0.60+git20150718-1kxstudio1

This seems to affect all Calf plugins in all hosts I tried. Is anybody expiriencing similar problems?

**Comment by boomshop** [comment]
The master branch has a broken UI atm. Please use the stable 0.0.60.

**Comment by unfa** [comment]
Ok, so it's a known issue. I backported to some earlier version and it works. The plugins are operatable anyway even in such state as on above picture, but I need to read all values below the knobs.

**Comment by unfa** [comment]
I hope  this issue can be solved soon.
