### ISSUE TITLE
Transient Designer misses the first transient

### ISSUE THREAD

**Issue by bdwarf** [calf-studio-gear/calf#219]
Hi,
I found that the Transient Designer sometimes misses the first transient on a track when the start of the track contains only silence. (for example programmed kick drum track)
When the start of the track is not complete silence, the Transient Designer is working as expected. I checked it with an added pink noise at -150db level.
Lookahead does not matter, I tried with 0 and 100 too.

OS: Ubuntu 18.04.2 LTS
DAW: Ardour-5.12.0 (installer from ardour.org)
Tested with calf-plugins 0.0.60-5 from package,
and calf-0.90.1 compiled from source.

![transient_miss](https://user-images.githubusercontent.com/47699042/52904661-4a206700-322f-11e9-93c6-29fe53e306eb.png)
![transient_ok](https://user-images.githubusercontent.com/47699042/52904662-50aede80-322f-11e9-83a3-84cc3b35b44a.png)

[audio.zip](https://github.com/calf-studio-gear/calf/files/2872338/audio.zip)

**Comment by boomshop** [comment]
Could you please test Chrischis fix in latest git and report back?

**Comment by bdwarf** [comment]
I tested the latest git, and everything is ok with the transient designer.
Thanks!

**Comment by boomshop** [comment]
Thanks for reporting back.
