### ISSUE TITLE
configure fails to detect lv2 >=1.16.0

### ISSUE THREAD

**Issue by dvzrv** [calf-studio-gear/calf#220]
From lv2 1.16.0 onwards, there's no more lv2core, but `configure.ac` relies on the check for `lv2core >= 6`.
It should be replaced by something like `lv2 >= 1.0`. I can open a pull request for that, if you want.

**Comment by boomshop** [comment]
Would be nice, thanks in advance!

**Comment by dvzrv** [comment]
Oh, I realize, this has already been done for `HEAD` in #213.
However, the version check there is questionable, as there is no `1.1.14`, but there's `1.14.0`. Is this maybe what @schnitzeltony was aiming at?

**Comment by dvzrv** [comment]
Also, this builds fine without changing the includes (as has been done in the above mentioned pull request), but I'm also not sure how long @drobilla will keep the `lv2.h` symlink around.

**Comment by drobilla** [comment]
There are no plans to remove the top-level `lv2.h`.
