### ISSUE TITLE
Calf plugins theme missing in Ardour 5.12 on Ubuntu Studio 18.10

### ISSUE THREAD

**Issue by viktorsmari** [calf-studio-gear/calf#221]
I suspect this is not a Calf problem, but maybe someone here knows.

The Calf plugins are not showing their theme in Ardour 5.12 on Ubuntu Studio 18.10.  They work but they look "plain".

Does anyone know what can cause this?

Calf Compressor:
![2019-03-05_22-04-41](https://user-images.githubusercontent.com/1689020/53837386-bd95d880-3f92-11e9-97a6-34a7fa43dc5d.png)

**Comment by boomshop** [comment]
Could you please add a screener to explain what you mean by "plain"?

**Comment by viktorsmari** [comment]
@boomshop just added it!

**Comment by boomshop** [comment]
Seems you have installed calf-ladspa package?

**Comment by viktorsmari** [comment]
Yes I installed it, and then I got a segmentation fault error, so I removed that package and installed only `calf-plugins` package. Is that the wrong way to do it?

**Comment by boomshop** [comment]
calf-ladspa is a dependency of lmms. If you have that installed maybe it pulled in calf-ladspa again?

**Comment by boomshop** [comment]
I would recommend using KXStudio repositories for your audio stuff to get the latest shtuff. FalkTX added a dummy package to work around this issue introduced by Debian maintainers.

**Comment by eeickmeyer** [comment]
This should be fixed in Ubuntu Studio 19.04 (due in April) since the package was upgraded to 0.90.1 and lmms has been dropped until the packaging situation can get straightened out. Ubuntu Studio 18.10 still has calf 0.60.

**Comment by boomshop** [comment]
Thanks a bunch for the information!

**Comment by viktorsmari** [comment]
I will wait for 19.04, reinstall from scratch and see if the issue is still relevant then.

Thank you!
