### ISSUE TITLE
visualization do not displaying

### ISSUE THREAD

**Issue by lagunax** [calf-studio-gear/calf#228]
sorry for boring, but can't figure what lib did not installed. Plugs works fine, but do not show part of windows where mast graphs be (jast blank window background). using debian9+xfce+kxstudio(latest kx deb repo)+claudia0.9.0+carla2.0.0+calf_plugs(2:0.90.1-1kxstudio4 lv2). tried other vertions of carla and calf, but nothing changes. allworks well on other pc with kde, but here nothing viewing.

**Comment by lagunax** [comment]
found old one issue #109, that is same, but do not see how to make visualization visible, or does it still not work in this case?

**Comment by boomshop** [comment]
Open Carla, go to Menu -> Settings -> Configure Carla -> Engine, disable "Use UI bridges instead of direct handling when possible", click "OK". Go to Menu -> Engine, click "Stop", click "Start".

**Comment by OliverEvans96** [comment]
Changing that setting had no effect for me - still no graphs.

**Comment by lagunax** [comment]
@OliverEvans96 check libraries. you have no some libraries, do not remember at all what kind of

**Comment by psabbag** [comment]
Hello, running Ubuntu 20.04 LTS, latest Carla and latest Calf plugins from repository. 
Same issue, no graphs in all Calf plugins. I already disabled UI bridges. No changes. No graphs.
Is any solution to this?
Thanks

**Comment by Gnlfz007** [comment]
No Calf GUIs on Ubuntu 20.04 with MusE 3.1! Somebody reported the same issue with Carla, in a closed thread. 
Is the version shipped with 20.04 broken or outdated? On 18.04 it worked without problems.
Ubuntu 20.04 will be widely used. To promote Calf, it would be a wise decision to address this issue.

**Comment by ansgoati** [comment]
@Gnlfz007 Same Calf Ui problem with Carla here on Arch but disabling "Use UI bridges instead of direct handling when possible" fix that. I think the issue is from the DAW, for example on Ardour the display for the eq 5 band is shown ok but on Qtractor the lines on the display sometimes are gone, you have to close and reopen the gui to see the screen lines on the freq response, is weird.

**Comment by Gnlfz007** [comment]
In my case it was a missing dependency; the following packets were missing: libgtk2.0-dev libgtkmm-2.4-dev when _building_ MuSE. So _my_ issue was not related to the plugins at all. Sorry for not stating this here. 

My post related to MusE:
https://linuxmusicians.com/viewtopic.php?p=119695
