### ISSUE TITLE
typos on the website

### ISSUE THREAD

**Issue by trebmuh** [calf-studio-gear/calf#23]
Hi guys, yesterday I reported a typo on the website to Krzysztof on the #lad channel on IRC. This was in Calf-reverb definition : artifficial -> artificial .
I found another one today in the Calf-mono-input definition : funtion -> function.
Since he's not on IRC right now and my brain would loose it in about 10 mins from now, I'm putting this here in the hope someone will pick it up soon.
HTH

**Comment by boomshop** [comment]
Thanks for both reports, fixed.
