### ISSUE TITLE
Request: Multitrack / Sidechain spectrum analyzer

### ISSUE THREAD

**Issue by ollyollyollyltd** [calf-studio-gear/calf#234]
First of all, thank you for all of your work on this amazing set of plugins!

For a while I have been looking for a Linux equivalent of Blue Cat's [FreqAnalyst Multi](https://www.bluecataudio.com/Products/Product_FreqAnalystMulti/).  It's a spectrum analyzer that displays multiple tracks on top of each other to make it easier to identify conflicting frequency bands between instruments.  This would be very useful for, for example, carving out spaces in a guitar mix for the vocals to sit.

It is currently possible to 'kind of' do this with the Calf Analyzer plugin, using sidechain inputs
- Put the plugin on it's own bus, with nothing routed to it
- Click 'pinout'
- Add two sidechain inputs, fed by instrument tracks
- Connect the sidechain inputs to the L and R audio in of the plugin
- Select 'analyzer stereo' or 'stereo image' on the main plugin (or any of the settings which will display L and R frequencies separately

This gives me a view of both of the tracks frequencies so I can compare and EQ a needed.

The limitation here is that I can only do two tracks.  Ideally I would like to have all of my main instruments routed to an analyzer so I can check to see that each of the has a 'main' place to live in the mix.

Since we can already add an arbitrary number of sidechain inputs to the plugin (I guess) the main work would be allowing an arbitrary (or fixed, but high) number of inputs to the plugin itself in place of the current L & R inputs, and for the front-end to detect and display them on the graph if there is signal present (maybe using different colours to differentiate them).

I hope this makes sense! Attached is a screenshot of the setup described above, with a fiddle on the left input and a mandolin on the right input.

![Screenshot at 2019-07-27 09-28-56](https://user-images.githubusercontent.com/5054551/61992340-e3f90500-b054-11e9-91a9-e2c7bdf5ff1a.png)

**Comment by ollycross** [comment]
A note to anyone looking for something similar:
I have had some success using the above process with two instrument tracks, getting those two balanced and EQ'd to my taste, AUXing those to another BUS, and sidechaining _that_ bus to the L input of the analyzer, and the next track to the R input.  The analyzer then shows the (summed) frequencies of tracks 1 and 2 as the left input and the frequencies of track 3 on the right.  Once I've carved a space for track 3 in tracks one and 2, track 3 gets AUX'd to the bus and track 4 goes the R input.  Rinse and repeat for any remaining tracks.

This isn't ideal but you can still get a rough idea of where each 'new' track is conflicting with the existing ones.

**Comment by sadko4u** [comment]
@ollycross, maybe something similar will help you?
https://lsp-plug.in/?page=manuals&section=spectrum_analyzer_x12

**Comment by ollycross** [comment]
@sadko4u That is _exactly_ what I am looking for - I knew some Linux genius would have built one!

It would be great if Calf could implement a plugin with this functionality as part of their suite but if don't then this will do nicely!

Thanks :)
