### ISSUE TITLE
Vinyl sounds are not looping

### ISSUE THREAD

**Issue by marekjedrzejewski** [calf-studio-gear/calf#246]
In Arch Linux, on 0.90.3 all sound effects in vinyl plugin just run once and stops. Same thing with calf-git from AUR.

**Comment by theepotte** [comment]
Same problem here on Gentoo. Calf version 0.90.3

**Comment by NexAdn** [comment]
I have the same problem. Arch with `calf-git 0.90.3.r2574.0f45a436-1` from AUR.

**Comment by Porrumentzio** [comment]
Same in Manjaro 20.0.01, with Calf 0.90.3-1 version. Please solve this!

**Comment by iuriSpinassi** [comment]
Same here. My specs:
_Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.4.44-rt26-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
Memory: 15,4 GiB_

I'm using calf **0.90.3**

**Comment by lynerlok** [comment]
Same on fedora 33 and calf 0.90.3

**Comment by pemguin005** [comment]
Same issue in Ubuntu Studio 20.10, on Ardour 6.3.0. 

Running without Jack, using Alsa instead. No issues with any other Calf plugins, this is the first I've seen this. 

Plugin at defaults, if you enable any of the sound effects, (eg, Motor, Static, Noise, Rumble, etc), they play for 2-8 seconds or so (the length of their audio loop I'd imagine), and then they stop. Clicking to enable and disabled the same given sound will allow it to play again for it's given 2-8 seconds or so and then stops again.

All features of this plugin appear to work except for the looping sound effects.

**Comment by jerognlz** [comment]
Same problem with Debian 11. 

**calf-plugins                          0.90.3-1+b1**

**Comment by praashie** [comment]
The soundfont files didn't have looping enabled. I enabled looping with the other samples with Polyphone.

Here are the fixed soundfonts. Copy these files under `/usr/share/calf/sf2/`:
[Uploading vinyl_patched_sf2.zip…]()
