### ISSUE TITLE
Finding the html manuals installed with the plugins

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#25]
Manuals in my distro are in /usr/share/doc/calf/index.html not /usr/local/...

I was having trouble locating them.
I'm running KX Studio, maybe other distros put it elsewhere?

Could there be a way to add a "Manual" button somewhere that'll open the manual index?

**Comment by boomshop** [comment]
I added a hint to the README. Every plug-in has an entry in the "help" menu opening its very own HTML help page.
