### ISSUE TITLE
Deesser's Split mode broken?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#26]
I've been playing around with the awesome Calf deesser a lot  today (I had a very nasty track to fix).

I got a strong impression that in the Split Mode all I get is the original signal affected by a gentle lowpass filter and no matter how hard I drive the controls, I can't hear any difference to the signal at all. I think something is broken there.

I'm using the Git version from KX Studio repos. Does anybody have the same experience?

**Comment by boomshop** [comment]
I'm unable to confirm in stand-alone or different versions of Ardour with Debian and 0.0.60 or the latest git.

**Comment by unfa** [comment]
Maybe I should record a video showing my results.

**Comment by boomshop** [comment]
Yes, that probably could help in this case.

**Comment by boomshop** [comment]
Hey unfa, is this issue still an issue?

**Comment by unfa** [comment]
Nope. With recent Git version of Calf the split mode sems to process audio fine. I used it for a bass guitar to tame the string noise and it worked like a charm. However I'm not sure if the gain reduction meter displays correct values in that mode.
