### ISSUE TITLE
2 more tiny typos on the website

### ISSUE THREAD

**Issue by trebmuh** [calf-studio-gear/calf#28]
I spotted 2 more tiny typos on the website.

In "Compil from source" paragraph: there is: "Please enshure that your system meets all the requirements illustrated in the section "Dependencies"." -> "enshure" should be "ensure" ... unless this is done as a will :)

In "If you don't have any Linux available..." paragraph, there is: "This means you can run it whithout installation and install it later if you decide to." -> "whithout" should be "without".

Cheers.

**Comment by boomshop** [comment]
Hey trebmuh,

thanks a lot for the report, typos are fixed.

Cheers, Markus.

**Comment by trebmuh** [comment]
Sweet. Thanks.

**Comment by rekado** [comment]
A typo has returned: "...enshure that you have the following development packages installed" --- `s|enshure|ensure|`.

**Comment by boomshop** [comment]
Thanks for heads up!
