### ISSUE TITLE
Changing preset profiles at runtime

### ISSUE THREAD

**Issue by UgoPoddine** [calf-studio-gear/calf#292]
Hello,

having calfjackhost running in background after setting preset profile 1, e.g with calfjackhost eq8:eq_profile1 &, is there a way for changing at runtime (= without killing calfjackhost) the preset profile, for example calling calfjackhost eq8:eq_profile2 ?

Any help appreciated
Best regards
Ugo

**Comment by boomshop** [comment]
Unfortunately not.

**Comment by UgoPoddine** [comment]
Thank-you boomshop for the answer,

and I suppose that (especially in the case of eq8 add-on), there is no other alternative for performing the change, eg. via telnet connection command (like in VLC) or via MIDI machine-control messages to get this result, isn't it ?

Thank-you
Ugo

**Comment by boomshop** [comment]
No sorry, no chance to switch presets on runtime without using the UI :/

**Comment by UgoPoddine** [comment]
Thank-you

Best regards
Ugo
