### ISSUE TITLE
Unable to Set The Gain Properly From the Preset File

### ISSUE THREAD

**Issue by BrandonR541** [calf-studio-gear/calf#293]
I'm not sure if this is exactly the type of issue that is supposed to be posted here because the software works fine, but I have a question for the developers regarding the gain values in the .calfpresets file.

I have written a script to automatically create a Calf EQ12 preset from the speaker correction filters generated by REW (room eq wizard) measurements.

The Calf EQ presets allow for gain values between -36.1db and 36.1db, but the preset files convert those gain values such that:
-36.1db == 0.015625
0db == 1
36.1db == 64

The relationship between the EQ gain value and the preset file value is not linear, and I have not been able to figure out how exactly they are mapping these values after reading through the source files.

If the developers (or anyone else) can tell me how to map those values such that I can convert the gain values from REW to the level values needed for the Calf presets file, I would be extremely grateful, but thank you for the great software regardless.

**Comment by boomshop** [comment]
See explanation here:
https://www.electronics-notes.com/articles/basic_concepts/decibel/basics-tutorial-formula-equation.php

Use calculator here (voltage):
https://circuitdigest.com/calculators/decibel-db-calculator

Approximation:
8 = 18dB
4 = 12dB
2 = 6dB
1 = 0dB
0.5 = -6dB
-0.25 = -12dB
-0.125 = -18dB
0.5 = -6dB

**Comment by BrandonR541** [comment]
Thank you!!
