### ISSUE TITLE
Automating calf plugins in ardour can cause ardour to segfault

### ISSUE THREAD

**Issue by spectromas** [calf-studio-gear/calf#30]
This seems to be fairly consistent and reproducible for me: 

1. open a new ardour session
2. load multi chorus on the master channel
3. create automation for dry amount and set to 'play'
4. add an audio channel (sometimes it segfaults straight away here)
5. click on the tracks alternately which the song is playing, after a few clicks ardour segfaults. 

I don't know if it is just multi-chorus but that (and the parameters mentioned) is the one I have been working with when this happened. I think that the more parameters you automate the quicker and more consistent the crashing becomes. 

Ardour prints this out in a terminal when this happens: 

    (ardour-4.2.0:21361): Gtk-CRITICAL **: IA__gtk_adjustment_set_value: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
    
    (ardour-4.2.0:21361): Gtk-CRITICAL **: IA__gtk_widget_get_action: assertion 'GTK_IS_WIDGET (widget)' failed
    
    (ardour-4.2.0:21361): Gtk-CRITICAL **: IA__gtk_widget_set_tooltip_markup: assertion 'GTK_IS_WIDGET (widget)' failed
    
    (ardour-4.2.0:21361): Gtk-CRITICAL **: IA__gtk_adjustment_set_value: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed
    
    (ardour-4.2.0:21361): Gtk-CRITICAL **: IA__gtk_widget_get_action: assertion 'GTK_IS_WIDGET (widget)' failed
    
    (ardour-4.2.0:21361): Gtk-CRITICAL **: IA__gtk_widget_set_tooltip_markup: assertion 'GTK_IS_WIDGET (widget)' failed *** Error in `/usr/lib64/ardour4/ardour-4.2.0': corrupted double-linked list: 0x00000000074b6040 ***

It goes on with more information but I don't know if it is relevant here - http://pastebin.com/gXXGLe9j

I've been in contact with rgareus from the ardour dev team and it seems this is a semi known issue:

>we were not able to track this down.  but everything points that  calf just writes to some memory  where it should not write to..

He did mention another similar issue but the solution (using 0.0.60) makes no difference for me - http://tracker.ardour.org/view.php?id=6511#c17045 

I was initially using the latest git version of calf plugins but downgraded and got the same problem. I am using Ardour 4.2.

**Comment by boomshop** [comment]
I am currently running Ardour 4.4.0 and the latest master ( f444d58eeee ) - works for me. Do you have the chance to upgrade and test it with a newer version of Ardour?

The video shows two tracks with Multi Chorus and Phaser and four randomly automated ports each, according to your description this should crash?

http://calf-studio-gear.org/stuff/vokoscreen-2015-11-09_10-56-54.avi

**Comment by spectromas** [comment]
This actually turned out to be ardour, one of the ardour devs managed to track down the problem and fix it so this bug can be closed. I just checked again with the latest nightly build of ardour with 0.60 calf and I can't reproduce it any more. 
Thanks.
