### ISSUE TITLE
Feature request: mono-input module autoconnect

### ISSUE THREAD

**Issue by moon8orange** [calf-studio-gear/calf#301]
Hi, first of all, the calf plugins are really awesome and super useful, I use them in my zoom meetings to tune up and reduce noise on my mic. It's really awesome (except for the zoom part, I would prefer to use jitsi).

So the feature which I think would be awesome is if there was a way to auto-connect the mono input module. Basically I want to start calfjackhost with an environmental variable (such as CALF_IN_1) set to my input mic and then have the mono-input module connect it's input to it. I've tried this and I get the error "Cannot connect input to plugin mono - the plugin no input ports"

I think it would be a really nice feature because the less setup I have to do before a zoom meeting, the less there is to go wrong.

currently this is how I'm starting calfjackhost:

env PIPEWIRE_LATENCY="128/48000" \
	CALF_IN_1="M Series Digital Stereo (IEC958):capture_FL" \
	CALF_IN_2="M Series Digital Stereo (IEC958):capture_FR" \
	CALF_OUT_1="Effects-Mic:input_FL" \
	CALF_OUT_2="Effects-Mic:input_FR" \
	pw-jack calfjackhost ! mono ! filter:natural-voice ! gate:stream !

**Comment by moon8orange** [comment]
I sort of implemented exactly what I was looking for after reading the code. It was really easy, but I'm not sure what you guys would think of it.

Anyways in host_session.cpp I modified the flow statements just after line 280. I edited it to... 

```
if (!i)
{
    if (plugins[0]->metadata->get_input_count() == 1)
    {
    	client.connect(getenv("CALF_IN_1")?getenv("CALF_IN_1"):"system:capture_1", cnp + plugins[0]->get_inputs()[0].name);
    } 
    else if (plugins[0]->metadata->get_input_count() == 2) 
    {
        client.connect(getenv("CALF_IN_1")?getenv("CALF_IN_1"):"system:capture_1", cnp + plugins[0]->get_inputs()[0].name);
        client.connect(getenv("CALF_IN_2")?getenv("CALF_IN_2"):"system:capture_2", cnp + plugins[0]->get_inputs()[1].name);         
    } else {
		fprintf(stderr, "Cannot connect input to plugin %s - the plugin no input ports\n", plugins[0]->name.c_str());
    }
}
```

It compiles and runs and satisfies my needs!

**Comment by boomshop** [comment]
What are you trying to achieve with Mono? Maybe you should try Stereo Tools, which is built for use-cases like this.

**Comment by moon8orange** [comment]
Well, I only use the front left capture on my device so it's really a single mono source (please disregard anything about the front right capture in the first post). I then want to apply a high pass filter, and a noise gate. Finally the audio gets sent out to a virtual source in pipewire where it can be used in a video chat client.

I did notice just now that I can simply connect the front left capture to calf input 1 and again to calf input 2. But it seemed like the mono input source was the most appropriate way connect a single mic.

**Comment by boomshop** [comment]
Yes, the latest description makes sense, connecting the left channel to left and right of the first effect. Mono is used in production environments like DAWs where you have a physical mono channel that you want to route to a stereo effect. In your case it is a physical stereo channel using just one channel of it.
