### ISSUE TITLE
[REQ] fix GH license settings

### ISSUE THREAD

**Issue by forart** [calf-studio-gear/calf#309]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Effects section](https://github.com/forart/HyMPS/blob/main/AudioFXs.md)), can you please set correct licensing terms for this git ?

Our "problem" is that does not generates the right badge: 

![](https://flat.badgen.net/github/license/calf-studio-gear/calf?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/calf-studio-gear/calf/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by JohannesLorenz** [comment]
@forart Hi. I think it takes the license from the file `COPYING`, which says "GNU LESSER GENERAL PUBLIC LICENSE". The source says the same. So I would indeed expect that the badge generates LGPL-2.1. Why do you think it is incorrect?

**Comment by forart** [comment]
Hi there, thanks for your reply.

As you can see above, it works correctly now.

Thanks again.
