### ISSUE TITLE
update apache2-bin on calf-studio-gear.org webserver

### ISSUE THREAD

**Issue by Cyborgscode** [calf-studio-gear/calf#327]
Hi,

you using an apache2 version 2.4.56 with two missing CVE patches. But don't panic, as long as you do not use proxy directives, it's not vulnerable. Debian offer 2.4.57-u2 packages, so you just can upgrade easily.

**Comment by boomshop** [comment]
Thanks for the information. I'll wait until stable offers an upgrade and no, I don't use proxies.
