### ISSUE TITLE
Feature request: Dark GUI themes

### ISSUE THREAD

**Issue by jrigg** [calf-studio-gear/calf#33]
It would be nice to have some darker GUI themes. I find that white or brightly coloured controls and buttons pull my eyes away from the important stuff like the meters and the line display. My own preference is for darker themes as I find them easier to work with. Here's an example:
![calf-jr1](https://cloud.githubusercontent.com/assets/6928427/10016233/4fe62440-611d-11e5-9b0c-0c361d688715.jpg)
![calf-jr1-bypass](https://cloud.githubusercontent.com/assets/6928427/10016241/5d4c15a4-611d-11e5-9432-76e02ed28f7f.jpg)

http://www.jrigg.co.uk/linuxaudio/download/plugin/calf-jr1-theme.tar.bz2

BTW the new theming setup is very easy to use :-)

**Comment by boomshop** [comment]
![Uploading Calf_Midnight.png…]()
There's a new style called "Calf Midnight" available in the git repository.

**Comment by jrigg** [comment]
Looks great. Thanks for adding.
