### ISSUE TITLE
Calf Fluidsynth crashes Ardour 8.2 with specific soundfonts

### ISSUE THREAD

**Issue by razcore-rad** [calf-studio-gear/calf#339]
This seems to happen with large soundfonts (>300mb). I don't know if it can be replicated, Ardour 8.2 just crashes with no terminal info immediately after selecting an `.sf2` file.

For example using [Essential Keys-sforzando-v9.6](https://drive.google.com/file/d/14b8Er8W2VFhJLYD8v6ZsOq6CgVxW3FWS/view?usp=sharing) from [Soundfonts 4U](https://sites.google.com/site/soundfonts4u/) crahes Ardour, while [Dore Mark's NY S&S Model B-v5.2](https://drive.google.com/file/d/1nvTy62-wHGnZ6CKYuPNAiGlKLtWg9Ir9/view?usp=sharing) does not. This only happens in Ardour, Calf JACK Host works just fine.

There are other soundfonts that crash as well, but I haven't tried very many, I just tried Ardour for the first time yesterday.

Let me know if I can do anything to debug this at my end.

I compiled both Ardour (tag 8.2) and Calf (tag 0.90.3) on my local machine so I don't think there's weird library inconsistencies. I did compile against `libjack-jackd2-dev` instead of `libjack-dev` and I use `pipewire` instead of `jackd`.

Anyway, if there's any method to produce a log that anyone can give me let me know! Or any other info that might be relevant. Thanks.

OS: **Ubuntu 23.10** Kernel Version **Linux 6.5.0-14-generic** GNOME Version **45.1** Windowing System **X11**

**edit**:
Oh forgot to mention that this is also the behavior with the official `calf-plugins` deb package

**Comment by JohannesLorenz** [comment]
Hi @razcore-rad . You could try master, though I guess this will not change anything here. Once you have master running with debug symbols, you could startup ardour with gdb, and when gdb stops at the crash, execute `bt` in gdb and send us the backtrace. However, I guess you already know all this :smiley: 

Another idea would be to try more DAWs. If only Ardour crashes, it could be an issue of Ardour. If many other DAWs crash, it could be an issue of Calf. E.g. Jalv is a minimal Lv2 host, or you could try Qtractor.

**Comment by razcore-rad** [comment]
True... I hoped I didn't have to involve a debugger, but I guess not. This isn't only an Ardour 8 problem, Carla also crashes with no error. I tried other MIDI sequencers/DAWs, the problem is most of them don't load the Calf FluidSynth interface so I can't even select assign the soundfont.

But I'm pretty on the verge of just not using it, after all Ardour does come with its own FluidSynth plugin so that should be fine. The other plugins I tried from Calf seem to be fine, although I didn't go through all of them.

Thanks anyway.

**Comment by razcore-rad** [comment]
I'll close this cause I can't reproduce this reliably, tried getting some logs with `ardour8 --debug all`, but I didn't see anything helpful. In any case this is still a problem I just don't know how to debug or produce useful logs even.
