### ISSUE TITLE
Knobs dont indicate values

### ISSUE THREAD

**Issue by zettberlin** [calf-studio-gear/calf#34]
In the recent versions of calf turning knob does not give visible feedback so it does not indicate the actual values, the knob is set to.

I thought, this could be an issue with the new white on white theme, as in: the png for the knobs simply dont show any visible notches to indicate values. But the problem is visible in the other themes as well...

I build today from git in Ubuntu 14.10

**Comment by boomshop** [comment]
As you can see in the screen shots on my blog it works for us:
http://mein-neues-blog.de/

Any usable output in the terminal when running calfjackhost?

**Comment by boomshop** [comment]
What do you mean "white on white"? Sounds like there are other problems with you build. Would be nice if you could provide a screen shot.

**Comment by zettberlin** [comment]
![calfoldtheme](https://cloud.githubusercontent.com/assets/9048260/10110758/9cfc795a-63cf-11e5-9e3d-23acba1581c3.png)

I do not get any visual feedback when turning the knobs. Everything else works just perfect.

white on white... just a joke, bro. I dont really like the white design, compared with the old one, but that is just personal taste.... no offence meant ;-)

**Comment by boomshop** [comment]
Sorry but I don't have no explanation for that right now. Please make sure that you are on the master branch and have the latest commit checked out (4d3fdeaf1dc9ed34fe7f1fadff5b75e0f5b26ddb). If everything should be fine please try to manually delete /usr/[local]/share/calf and do a `make distclean` before starting from scratch with autogen.sh.

**Comment by zettberlin** [comment]
Did that as you recommended, built like this:

./configure --enable-experimental

same results.

dpkg-query  -l *lilv*                                                   +++-=============================-===================-===================-================================================================
ii  liblilv-0-0                   0.16.0~dfsg0-1      amd64               library for simple use of LV2 plugins                   
ii  liblilv-dev                   0.16.0~dfsg0-1      amd64               library for simple use of LV2 plugins (development files)
ii  lilv-utils                    2:0.21.3+svn5718-1k amd64               library for simple use of LV2 plugins (runtime files)     
ii  python-lilv                   2:0.21.3+svn5693-1k all                 meta-package for python-lilv                              
ii  python2.7-lilv                2:0.21.3+svn5693-1k amd64               library for simple use of LV2 plugins (runtime files)     
un  python3-lilv                  <keine>             <keine>             (keine Beschreibung vorhanden)                            
ii  python3.4-lilv                2:0.21.3+svn5693-1k amd64               library for simple use of LV2 plugins (runtime files)

**Comment by jrigg** [comment]
@zettberlin in that screenshot is Monosynth running in calfjackhost or in an LV2 host (eg. jalv.gtk)?

**Comment by zettberlin** [comment]
It is running in calfjackhost. Looks about the same in recent Carla and Ardour4.2...

**Comment by jrigg** [comment]
If I start calfjackhost in xterm I get a lot of Gtk-CRITICAL plus a few GLib-GObject-CRITICAL warnings (although it still works fine here). Do you get any similar warnings which might give some clue?

**Comment by zettberlin** [comment]
I dont get no messages at all when starting calfjackhost or adding a plugin. 
In Carla I get:

Will use LV2 Gtk2 UI, NOT!     

And while loading CALF Monosynth:
                                                                                                     
CALF DEBUG: instance 0x29841c0 data 0x29831f0                                                                                       
CALF DEBUG: calf 0x7f7a99305610 cpi 0x7f7a988f9320                                                                                  
Send configures...                                                                                                                  
Trying to get window...
Match found using UTF-8 name
Match found using simple name

Other GTK2-UI Plugins such as Guitarix work as expected....

**Comment by boomshop** [comment]
Please try the following:

* Open src/ctl_knob.cpp in your local Calf git
* Search for line 135
* Change debug to 2
* Compile, install and run calfjackhost in a terminal
* Open one of the plug-ins and turn a knob
* Paste the hopefully appearing output here

**Comment by zettberlin** [comment]
Here we go, this is fluidsynth in calfjackhost:

Creating a blank synth
start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 378,00 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 381,44 end 405,00
fill from 381,44 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 378,00 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 381,44 end 405,00
fill from 381,44 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 378,00 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 381,44 end 405,00
fill from 381,44 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 378,00 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 378,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 378,00 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 381,44 end 405,00
fill from 381,44 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 379,08 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 379,08 (start 135,00 zero 135,00 phase 379,08 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 379,08 (start 135,00 zero 135,00 phase 379,08 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 379,08 (start 135,00 zero 135,00 phase 379,08 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 379,08 (start 135,00 zero 135,00 phase 379,08 end 405,00)
taken.
checking tick 4 405,00
finally! deg 379,08
tick 4 deg 379,08 last 381,44 end 405,00
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 379,08 (start 135,00 zero 135,00 phase 379,08 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 379,08 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 379,08 end 405,00
fill from 379,08 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 380,16 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 380,16 (start 135,00 zero 135,00 phase 380,16 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 380,16 (start 135,00 zero 135,00 phase 380,16 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 380,16 (start 135,00 zero 135,00 phase 380,16 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 380,16 (start 135,00 zero 135,00 phase 380,16 end 405,00)
taken.
checking tick 4 405,00
finally! deg 380,16
tick 4 deg 380,16 last 381,44 end 405,00
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 380,16 (start 135,00 zero 135,00 phase 380,16 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 380,16 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 380,16 end 405,00
fill from 380,16 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 381,24 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 381,24 (start 135,00 zero 135,00 phase 381,24 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 381,24 (start 135,00 zero 135,00 phase 381,24 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 381,24 (start 135,00 zero 135,00 phase 381,24 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 381,24 (start 135,00 zero 135,00 phase 381,24 end 405,00)
taken.
checking tick 4 405,00
finally! deg 381,24
tick 4 deg 381,24 last 381,44 end 405,00
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 381,24 (start 135,00 zero 135,00 phase 381,24 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 381,24 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 381,24 end 405,00
fill from 381,24 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 382,32 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 382,32 (start 135,00 zero 135,00 phase 382,32 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 382,32 (start 135,00 zero 135,00 phase 382,32 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 382,32 (start 135,00 zero 135,00 phase 382,32 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 382,32 (start 135,00 zero 135,00 phase 382,32 end 405,00)
taken.
checking tick 4 405,00
finally! deg 382,32
tick 4 deg 382,32 last 381,44 end 405,00
void from 381,44 to 382,32 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 382,32 (start 135,00 zero 135,00 phase 382,32 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 382,32 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 382,32 end 405,00
fill from 382,32 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20

start 135,00 end 405,00 last 135,00 deg 135,00 tick 0 ticks 5 phase 384,48 base 270,00 nend 0,00
tick 0 0,00
tick 1 0,60
tick 2 0,80
tick 3 0,90
tick 4 1,00
tick 0 deg 135,00 last 135,00 end 405,00
tick from 133,85 to 136,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 384,48 (start 135,00 zero 135,00 phase 384,48 end 405,00)
taken.
checking tick 1 297,00
finally! deg 297,00
tick 1 deg 297,00 last 138,44 end 405,00
fill from 138,44 to 293,56 @ 1,00
tick from 295,85 to 298,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 384,48 (start 135,00 zero 135,00 phase 384,48 end 405,00)
taken.
checking tick 2 351,00
finally! deg 351,00
tick 2 deg 351,00 last 300,44 end 405,00
fill from 300,44 to 347,56 @ 1,00
tick from 349,85 to 352,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 384,48 (start 135,00 zero 135,00 phase 384,48 end 405,00)
taken.
checking tick 3 378,00
finally! deg 378,00
tick 3 deg 378,00 last 354,44 end 405,00
fill from 354,44 to 374,56 @ 1,00
tick from 376,85 to 379,15 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 384,48 (start 135,00 zero 135,00 phase 384,48 end 405,00)
taken.
checking tick 4 405,00
finally! deg 384,48
tick 4 deg 384,48 last 381,44 end 405,00
void from 381,44 to 384,48 @ 1,00
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 135,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 384,48 (start 135,00 zero 135,00 phase 384,48 end 405,00)
checking 405,00 (start 135,00 zero 135,00 phase 384,48 end 405,00)
taken.
checking tick 4 405,00
finally! deg 405,00
tick 4 deg 405,00 last 384,48 end 405,00
fill from 384,48 to 401,56 @ 0,20
tick from 403,85 to 406,15 @ 0,20


And so on, the knob graphics do not indicate nuthin...

**Comment by boomshop** [comment]
I extended the debug output. Please pull in the latest changes from the git repo and repeat the debugging. Note that the debug flag has moved to src/calf/ctl_knob.h line 40 now.

**Comment by zettberlin** [comment]
Cewl, still looks kinda crazy but now the indicator is back again, like this:

![calf_fsynth_debug](https://cloud.githubusercontent.com/assets/9048260/10147395/04c5bc12-662e-11e5-96d4-2d08c38f9e54.png)

**Comment by boomshop** [comment]
Does it work with disabled debug output, too?

**Comment by zettberlin** [comment]
Works perfectly well.
I like the notches in the margins of the smaller Knobs too, pretty OK on the bigger knobs also. It also works perfectly well with the new, white theme. BTW: with these new notched margins the new theme looks much more ergonomic to me. Thanks a lot!

**Comment by zettberlin** [comment]
Works perfect in Carla also, I consider this one closed, sir.

**Comment by boomshop** [comment]
Great to hear that.

Cheers!
