### ISSUE TITLE
Add Full Name to Arch Linux Package Description

### ISSUE THREAD

**Issue by brooksvb** [calf-studio-gear/calf#350]
Please consider adding the full name "Calf Studio Gear" in the description of the Arch Package so when I search for it it will come up. Otherwise, I had to track down what the actual package name was on your website.

Thanks!

**Comment by JohannesLorenz** [comment]
@brooksvb You mean the "Description" field of https://archlinux.org/packages/extra/x86_64/calf/ should be changed from "LV2 plug-in suite and standalone Jack host" to "Calf Studio Gear"? If yes, this is out of our responsibility: This can only be done in the Arch git repo: https://gitlab.archlinux.org/archlinux/packaging/packages/calf/-/blob/main/PKGBUILD?ref_type=heads . Can you please make an issue / a PR there?

**Comment by JohannesLorenz** [comment]
@brooksvb ?

**Comment by brooksvb** [comment]
I was going to create the issue on their repo, but found myself stuck in a convoluted process to receive an account capable of doing so.
