### ISSUE TITLE
Feature Request: Single Pole Allpass Filter

### ISSUE THREAD

**Issue by ReubenM** [calf-studio-gear/calf#36]
This plugin would be a little boring since it would mostly be a utility plugin to correct phase shifting problems instead of an effect.

I can find no plugin where I can set a start frequency, and a stop frequency, and within that range it would rotate the phase from 0 to a user defined rotation between -180 and 180 degrees.

So for instance, if I set the start frequency at 1k and set the stop frequency at 5k, with the phase rotation set to +60, the phase would start rotating at 1k and would have rotated to +60 degrees by the time it reached 5k, and then everything past 5k would stay fixed at +60 rotation. If the stop frequency was set below the start frequency, the phase rotation would extend past the stop frequency in the opposite direction. Would probably need an option for linear / log / other(?) interpolation between the start and stop frequencies.

The closest thing I can find is the 4x4 allpass filter by Steve Harris, but it is an effect and can't be controlled in a way that is useful for fixing phase shift.

**Comment by ReubenM** [comment]
Found a way to effectively deal with this. (And is probably far too specific a feature for this plugin suite anyway)

**Comment by trebmuh** [comment]
@ReubenM : how did you manage this finally?

**Comment by ReubenM** [comment]
https://sourceforge.net/projects/rephase/

**Comment by trebmuh** [comment]
Thanks. I was very excited at looking at it. Unfortunately, its neither open source and/or libre software.

**Comment by ReubenM** [comment]
Yes, the only open source project I'm aware of that has a similar scope to rephase is qloud. http://gaydenko.com/qloud/

But it is strictly for digital room correction, so it's all automated and doesn't offer any toolset for manually manipulating the corrective impulse response that is generated. The manual manipulation available in rephase extends it's usage for purposes outside of DRC.
