### ISSUE TITLE
git-master: equalizer draggable graph handlers can't be dragged with mouse

### ISSUE THREAD

**Issue by Fak3** [calf-studio-gear/calf#37]
Hi. I installed current git-master version (f420ec32c1b567272b44d4d3f2f21700ca70f572) and using Ardour 4.2
When i use calf 12-band equalizer, i can see the mouse handlers in the graph, they show tooltips and cursor becomes 'drag', when hovering over them with mouse. But i can't drag them (not sure if this is how it should work). Those handlers move only when i change the corresponding filter sliders and knobs (below the graph), but not with mouse on the graph.
The same issue with all *-band equalizers

**Comment by boomshop** [comment]
Hey,
unfortunately I'm unable to reproduce it in Ardour 4.2.358. A couple of spontaneous questions:
* Your distribution?
* Your desktop environment?
* Does it work in the stand-alone version?
* Does the cross hair work? (Click the line graph once to enable, drag around, click once more to disable)

**Comment by Fak3** [comment]
Mine ardour is 4.2.0 (but this is probably irrelevant, as calfjackhost has the issue for me too)
* distribution: openSUSE
* DE: KDE 4.14
* i just tried with calfjackhost, but it also does not work there
* cross hair does not work

**Comment by boomshop** [comment]
* Does the scroll wheel work when hovering a handle? It should set the Q.
* Does adding the line `printf("foo\n");` in src/ctl_linegraph.cpp at line 1141 give any output when moving the cursor over the line graph in calfjackhost?

**Comment by Fak3** [comment]
* yes, scroll wheel works, sets the Q
* yes, i get tons of "foo" in console now

**Comment by Fak3** [comment]
i put some more prints inside calf_line_graph_button_press() and have some suspicious results:

when i click on the handle, i noticed that code never enters this block:
at line 1212:
```
int i = calf_line_graph_get_handle_at(lg, lg->mouse_x, lg->mouse_y);
if (i != -1)
{
  WILL NEVER GET THERE. 
  i IS ALWAYS -1
}
```

**Comment by Fak3** [comment]
more strange results from calf_line_graph_get_handle_at():

```
# these are tons of calls of calf_line_graph_get_handle_at() while hovering the graph inside handle
# everything looks fine here, handler will be returned, as condition is met
# sqrt(dx * dx + dy * dy) < HANDLE_WIDTH / 2.0
mouse_x 189.000; dx 0.000;  dy -14.000;  sqrt 14.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -11.000;  sqrt 11.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -9.000;  sqrt 9.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -8.000;  sqrt 8.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -7.000;  sqrt 7.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -6.000;  sqrt 6.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -5.000;  sqrt 5.000;  HANDLE_WIDTH 20.000
mouse_x 189.000; dx 0.000;  dy -4.000;  sqrt 4.000;  HANDLE_WIDTH 20.000

# now this is when i cliked the handle
# mouse_x here is -1.0
# so no handle will be returned, as coordinates are wrong
mouse_x -1.000; dx -190.000;  dy -115.000;  sqrt 222.092;  HANDLE_WIDTH 20.000

```

**Comment by boomshop** [comment]
Thank you very much.

**Comment by Fak3** [comment]
No, thank you for the support and this great software =)
