### ISSUE TITLE
[calfjackhost] "Remove" button doesn't display text

### ISSUE THREAD

**Issue by jrigg** [calf-studio-gear/calf#47]
"Remove" button in calfjackhost no longer displays correct text. Screenshot attached.

![calfjackhost-screenshot](https://cloud.githubusercontent.com/assets/6928427/11900104/8e64ffb2-a59b-11e5-9152-a039f2d1458b.jpg)

**Comment by jrigg** [comment]
That was quick!
Thanks for fixing.

**Comment by boomshop** [comment]
You're welcome, thanks for reporting.
