### ISSUE TITLE
Stereo tools plugins M/S mode not working properly

### ISSUE THREAD

**Issue by sapista** [calf-studio-gear/calf#5]
Hi, just testing Mid side modes in stereo conversions tools and I've realized that LR->MS and MS->LR mode are not working fine. I was expecting something like:
M = 0.5*( L + R )
S = 0.5*( L - R  )
L = M + S
R = M - S
However it seams it is working erratically. I've set up a stereo test signal to a Stereo Tools plugin working in LR -> MS mode. The output is connected to another Stereo Tools plugins working in MS -> LR mode. At the end I expect obtaining exactly the same stereo test signal but instead I got a signal with completely mixed L and R channels. 

In order to dig a bit more, I've read the source code of the plugin. The file "src/calf/modules_tools.cpp" line 193 have the following code:

            // LR/MS
            L += LL*L + RL*R;
            R += RR*R + LR*L;

The MS/LR conversions seams to be controlled by LL, RL, RR and LR constants. In fact, calculating such values seams thatsthe implementation is wrong for MS modes. Not tested for other modes or balance/pan settings, however I think it should look more like:

            // LR/MS
            M  = LL*L + RL*R;
            S = RR*R + LR*L;

Please note that I've removed the += and used new vars (M, S) to avoid overriding L R values during conversions. I don't know if I'm 100% right about the purposed implementation, but I think you should take it in consideration to review your code.

Thanks for your plugins pack, great work!

**Comment by boomshop** [comment]
Thanks for the report. This is fixed in master branch. Please note that the master actually slightly breaks the UI.
