### ISSUE TITLE
Add external inputs to sidechain compressor/gate/limiter

### ISSUE THREAD

**Issue by ampetrosillo** [calf-studio-gear/calf#53]
It would make these plugins very useful for ducking, for example. As of today, the only sidechain compressor with external inputs on Linux is the LADSPA SC3 plugin, which is quite basic. Or take for example sidechaining on the multiband gate, in order to reduce maybe spillage the snare onto the tom tracks (but only affecting the high end). It would also be handy to have lookahead on all the dynamics plugins (especially on the gate). It appears that the code for the functionality is already there (I see lookahead functionality on some of the plugins, external sidechaining would have to be added but it is probably trivial).

**Comment by boomshop** [comment]
The sidechain devices already have sidechain inputs.
![calf_jack_host](https://cloud.githubusercontent.com/assets/12529902/12469906/1d1b94b4-bff0-11e5-97d3-0753322b68ac.png)

**Comment by ampetrosillo** [comment]
Oh, couldn't find any mention of this in the manual.
Anyway, how about adding lookahead to the gates and compressors?

**Comment by boomshop** [comment]
The manuals aren't complete nor up-to-date. Feel free to enhance them.

It's much better for keeping track of feature requests or bug reports if there's one issue per topic. Since this main topic is a non-issue no one would look into it expecting to find another feature request.
