### ISSUE TITLE
Incomplete GUI when running inside Carla

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#55]
![calf carla](https://cloud.githubusercontent.com/assets/491704/12509084/5d795df0-c100-11e5-974b-555d4a0648c1.png)

When I'm using Calf plugins with Carla plugin host, some parts of the GUIs are not drawn at all. Mostly this is bearable (compressors don't display the curve and dancing dot), however looks like multibands use this graph to set  crossover frequencies, so some important functionality is missing because of this. No idea why this happens so.

Can anybody confirm this?

**Comment by falkTX** [comment]
This is normal.
The UIs (being gtk based) are ran in a separate process for safety.

You can make it run on the same process by unchecking the carla's engine "Use UI bridges..." option.

When Calf UIs start using atoms and drop instance-access this will no longer be an issue.
