### ISSUE TITLE
Suspision: Calf causes Ardour 4 to crash X?

### ISSUE THREAD

**Issue by unfa** [calf-studio-gear/calf#56]
Here's a bug I reported for Ardour about this:
http://tracker.ardour.org/view.php?id=6747

The thing is, Ardour recently crahes when I either try to add a Calf pluginf from a favourites list, or select a track, that makes Ardour display a list of plugins (with Calf plugins used there) that are applide to that track.

I suspect the problem might be that recent git version of Calf plugins are mishandling some events from the DAW in such a way that... X server blows up.

I first suspected Ardour, because after upgrade this started to happen. Then I recovered my system from backup with older version of Ardour kept there, but I updated Calf plugins, and the problem came back.

**Comment by boomshop** [comment]
Are you experiencing it with a fresh Ardour session? The plugins sometimes aren't backward compatible in some hosts because some of them handle ports by ID not by name. But that shouldn't crash X at all. This problem was addressed in Ardour lately and should be fixed in future builds as far as I got things right (Krzysztof, please correct me if I'm wrong).

**Comment by unfa** [comment]
Well the session I'm experiencing this is isn't too old: 10 days?

I just downgraded Calf plugins to non-git version, will see it it still hapens.

**Comment by boomshop** [comment]
It was meant more like you made a session, upgraded Calf and re-opened the the session afterwards - then it might happen that e.g. Ardour crashes.

**Comment by unfa** [comment]
Yes, I think I upgraded Calf plugins in the middle of working on this session.

**Comment by boomshop** [comment]
This is a problem hosts should take care about since parameters in plugins can change with newer versions. But as I said - afai understand Ardour has already nailed it down.

**Comment by unfa** [comment]
I upgraded Ardour and I'm using a non-git version of Calf plugins as packaged in KX Studio: Package: calf-plugins 2:0.0.60-2kxstudio1

The problem seems to be gone now.

**Comment by boomshop** [comment]
Great, thanks for leaving a note.
