### ISSUE TITLE
Some uses of uninitialized variables

### ISSUE THREAD

**Issue by oswald2** [calf-studio-gear/calf#57]
Recently, while tracking down a crash in Ardour, I came across some uninitialized uses of variables (most probably in if's). Probably not a big issue, but worth to look at. Find attached the valgrind output of loading a session in Ardour (which crashed, though not because of calf). 

[Calf Plugins Bug Report2.txt](https://github.com/calf-studio-gear/calf/files/101133/Calf.Plugins.Bug.Report2.txt)

**Comment by kfoltman** [comment]
It should be fixed in the current git. Could you re-test it?

**Comment by oswald2** [comment]
I can confirm, that the issue is fixed.

**Comment by boomshop** [comment]
Thanks for the report and the fix!
