### ISSUE TITLE
Multiband gate not effective

### ISSUE THREAD

**Issue by naptastic** [calf-studio-gear/calf#58]
up-to-date master, commit cf5a86b. What works: Bypass and solo for each band (though bypass mutes the band; I would have expected it to just pass through.) What doesn't work: No matter what settings I dial in, no gain reduction is ever indicated, and using an analyzer + my ears, I can't discern any change in sound. Is there an activation button I'm missing?

The single-band gate works as described.

**Comment by boomshop** [comment]
master of 08/01/15 far from up-to-date, latest commit is e55a9928d of 01/23/16.

As the screenshot states - works for me. How do you use it?

![calf_multiband_gate](https://cloud.githubusercontent.com/assets/12529902/12697408/8e12f1aa-c782-11e5-8135-e6bd387c280c.png)

**Comment by naptastic** [comment]
Ah-hah! I was using the wrong repository: http://repo.or.cz/r/calf.git

I added the correct repository and rebuilt, and it's working great. And sooooo many new features! Thanks!

**Comment by boomshop** [comment]
You're welcome!
