### ISSUE TITLE
Labels for plugin instances in Calf Host

### ISSUE THREAD

**Issue by borgdylan** [calf-studio-gear/calf#6]
Would it be possible to allow labeling of plugin instances in the calf jack host UI?. When you have more than one instance of a particular plugin it can get confusing when trying to see what plugin instance is for for example having gates for both the kick drum and snare.

**Comment by falkTX** [comment]
note to @boomshop there is a replacement for jack_set_port_name already.
See http://jack-audio.10948.n7.nabble.com/Jack-Devel-jackaudio-headers-23c299-add-new-public-API-jack-port-rename-td18559.html

both jack1 and jack2 provide this api right now, although both need to be in their latest git versions.

**Comment by boomshop** [comment]
Thanks for the information! We'll switch over when the new API was deployed.
