### ISSUE TITLE
Calf Organ: midi notes >= 96 have wrong frequency

### ISSUE THREAD

**Issue by audetto** [calf-studio-gear/calf#61]
I've used Calf Organ 0.0.60 and noticed that for some (most) preset instruments midi note above 96 just repeat the octave 84-95

C 96 is the same as C 84
D 98 is the same as D 86

and the next C repeats again C 84

I check with Calf analyser and you can see the spectrum going up and then suddenly going back to C 84
I have checked as well midi messages and the correct one gets reported (and other synthesisers work properly).

**Comment by boomshop** [comment]
AFAIK this is a feature not a bug. But Krzysztof knows more.

**Comment by kfoltman** [comment]
http://www.dairiki.org/HammondWiki/HarmonicFoldback

**Comment by kfoltman** [comment]
By the way, in Calf Organ there is a knob to adjust that effect.
