### ISSUE TITLE
Calf EQ 30 bands not working everywhere

### ISSUE THREAD

**Issue by trebmuh** [calf-studio-gear/calf#63]
Hi all,
I didn't investigate too far, but it does look that the 30 bands EQ is working with jalv, with calfjackhost, but not with Ardour (4.6 here) neither with Qtractor (0.6.7 maybe a bit old, I might try to update this one to a current version and re-test).
Both in Ardour and Qtractor, the "In level" and "Out level" are working fine as well as the bypass buton. But the 30 bands are not working at all.
Any idea ?

**Comment by boomshop** [comment]
This should have been fixed with 1f67f295d6dfc2543edaba6540dd52da862f71a8
I've tested it with Ardour 4.7 and the latest git build, works for me. Is this still an issue?

**Comment by trebmuh** [comment]
I'll check this soon and will report back to you.

**Comment by pms967** [comment]
I had that same problem too... gone after installing new version (calf-plugins-git 2:0.0.60+git20160727-1kxstudio1).

**Comment by trebmuh** [comment]
@boomshop : rebuild from today's GIT (https://github.com/calf-studio-gear/calf/commit/72b13fa8670738e735184494554a9d6f3fad56ac) and it's gone. Thanks guys!
I'm closing this bug then.
