### ISSUE TITLE
Fluidsynth should stream samples from disk

### ISSUE THREAD

**Issue by cyberbeat** [calf-studio-gear/calf#64]
I tried to load a huge sf2 file into fluidsynth, but my pc swapped to death. It would be nice, if your plugin could stream the sf2-samples from disk.

**Comment by boomshop** [comment]
It is just an implementation of FluidSynth (http://www.fluidsynth.org/) so you should probably file a feature request upstream. But i think it's quite impossible with this kind of architecture as this paper states: http://lac.linuxaudio.org/2011/papers/45.pdf But i might be wrong.
