### ISSUE TITLE
New Vintage Delay doesn't understand saved Parms from 0.60

### ISSUE THREAD

**Issue by suedwestlicht** [calf-studio-gear/calf#66]
When I load a song into Qtractor (DAW shouldn't be important) that is saved with the 0.60 Vintage Delay then the parms are not understood, e.g. "Wet", "Time R", "Medium", "Width". I add two screenshots, new and old:

![after](https://cloud.githubusercontent.com/assets/5550538/14376862/6c581b38-fd6c-11e5-8c68-40d71ac1d934.png)
![before](https://cloud.githubusercontent.com/assets/5550538/14376861/6c17c7cc-fd6c-11e5-97d3-da7a35ec47ca.png)

Regards
Holger Marzen

**Comment by boomshop** [comment]
This problem affects a couple of plugins. The changes introducing the issue clearly was a bad decision. We will do our best to avoid problems like these in the future but rolling everything back would lead to even more problems and inconsistencies. So sorry - but "won't fix".
