### ISSUE TITLE
Multiband enhancer prevents Ardour from exporting

### ISSUE THREAD

**Issue by matze** [calf-studio-gear/calf#69]
I used the enhancer on Ardour's master bus with great success, however when I tried to export a mixdown it just got stuck (no message on stdout/stderr) and I had to cancel the export.

**Comment by boomshop** [comment]
Worked for me on lots of exports by now. I'm not aware how to debug Ardour in this case but some more information seems necessary in this case.

**Comment by JonnyCodez** [comment]
Hi,
I saw this bug too. To work around it, ensure that the plugin windows are closed when you export. You will need to cancel the export in progress and delete the file in the export directory. 

You will then have full control of your ardour session again and the export will work as normal.

**Comment by boomshop** [comment]
Is this still an issue with latest git? Works for me even with visible Multiband Enhancer window.

**Comment by matze** [comment]
I will check during the weekend.

**Comment by boomshop** [comment]
No response for > 15 months so I'll close the issue. Feel free to re-open if you still have these issues.
