### ISSUE TITLE
Calf host needs bypass buttons per plugin

### ISSUE THREAD

**Issue by prokoudine** [calf-studio-gear/calf#7]
The title really explains it all: please add a bypass button per audio plugin to calf-jack-host. Right now if you want to disable an effect, you have to reroute stuff. That's rather tedious.

**Comment by trebmuh** [comment]
I'm adding my voice to this one.

**Comment by boomshop** [comment]
d957308b brings all kinds of controls to the rack interface. Still one issue left: widgets don't update their counterparts between rack and plug-in by now. We'll sort it out.
