### ISSUE TITLE
calf crashes when trying to open a formerly saved session

### ISSUE THREAD

**Issue by synthnassizer** [calf-studio-gear/calf#75]
calf version is current from github.  version 0.0.60 does not have this problem
attempt was made on xubuntu 14.04.

I go to file->open and load a calf rack session that was saved by the same current git version. Note that the saved session can be successfully loaded in calf 0.0.19 and 0.0.60.
The following messages appear in console: 
nass@starport:~/dev/calf$ calfjackhost 
Size 7
Loading reverb
Loading vintagedelay
Loading multibandcompressor
Loading multichorus
Loading phaser
Loading flanger
Loading analyzer
Segmentation fault (core dumped)

if this is an intermediate unstable commit to the git repo, please discard this issue.

**Comment by boomshop** [comment]
The session file could be helpful in this case.

**Comment by synthnassizer** [comment]
here is the calf rack session
[cr_sd2b.zip](https://github.com/calf-studio-gear/calf/files/312935/cr_sd2b.zip)

**Comment by synthnassizer** [comment]
perhaps I should also note that during configure stage, I have enabled sse.

**Comment by boomshop** [comment]
Thanks, crashes for me, too. Seems to be a problem with Analyzer, as soon as it is commented out the session file works as expected. Saving a new session with only one Analyzer crashes as well on re-opening.

**Comment by synthnassizer** [comment]
yup, I was running tests in parallel. I can confirm the problem is located in the analyzer loading stage.

**Comment by boomshop** [comment]
Is this still an issue with latest git?

**Comment by boomshop** [comment]
Thanks for reporting back!
