### ISSUE TITLE
[Feature Request/Question] Analyzer - Frequency range

### ISSUE THREAD

**Issue by d3rped** [calf-studio-gear/calf#76]
I'm currently working with some "high frequency" signals, sadly the calf analyzer seems to cap around 20kHz (which makes sense as we can't hear anything above it).
Anyways it would be nice if the frequency range could be set in the analyzer.xml file, or if it would be possible to set it in some other way instead of it being hard coded... at least I guess it is.

So depending on if it is already implemented this is either a question of how to set it or a feature request.
Thanks a lot.

**Comment by boomshop** [comment]
This seems to be a huge overhaul as Chrischi stated lately. Calf Analyzer is a pure audio signal analyzer and not meant to be used with signals above the human audible range.
