### ISSUE TITLE
lv2 ttl are invalid

### ISSUE THREAD

**Issue by x42** [calf-studio-gear/calf#79]
reminder: Upcoming liblilv will refuse to index or load any plugins that do not validate.

Calf 413bd43047 LV2 still has `Found 131 errors among 153 files (checked 39940 restrictions)`
Most of the plugins will not load anymore.

Please see http://lv2plug.in/pages/validating-lv2-data.html

**Comment by boomshop** [comment]
Most of them are fixed now via 4065eacc9, only 7 left which have to be revised by Krzysztof.
