### ISSUE TITLE
Ardour wont open session with multiple calf EQ plugins active

### ISSUE THREAD

**Issue by VinceLewis** [calf-studio-gear/calf#80]
Using Ubuntu Studio 14.04, calf 0.0.60, AMD 64 bit architecture, Ardour 3.

I am using multiple calf EQs in a project (5 band and 12 band). Also bass enhancer and reverb.
A previously working ardour session wont open. I did some googling and this has been noticed before, the ardour forum guesses it's to do with non-threadsafe library used in the compressors. Please see this page:

https://community.ardour.org/node/8271

It also mentions building the calf plugins from source, which I did, but that has not fixed the issue. 

The workaround is to set the calf eqs to active="no" in the XML of the ardour session files using a text editor. Then re-enable when the session opens. 

This workaround works for me, but obviously not ideal when I come back to them in the future as I wont know what plugins should be active.

**Comment by boomshop** [comment]
The linked thread targets a problem that was fixed long ago and which has nothing to do with compressor or EQ. Might it be that you updated the plugins in the meantime? We had some problems with backward-compatibility which might still exist.

**Comment by VinceLewis** [comment]
Okay, which version of plugins should I be using? I'll then re-download and
install.

**Comment by boomshop** [comment]
We recommend either the stable version which is 0.0.60 or a build from this repository if you know what you're doing.

**Comment by VinceLewis** [comment]
I am using 0.0.60 :(

**Comment by boomshop** [comment]
Did you update after creating the implied session and before the error occurred the first time?

**Comment by VinceLewis** [comment]
sequence of events:

Create session in Ardour 3.
use default calf plugins supplied with UbutnuStudio 16.01
report bug when re-opening session
download and make 0.0.60
change XML for existing ardour session to "active=no" for EQ plugins
re-open (works)
save
close
re-open (fails)


Do I need to create a new ardour session then?

**Comment by boomshop** [comment]
You could test the following:

* Copy the Ardour session file in a way that it opens
* remove all error-generating plugins
* try if everything else works well then
* add a new EQ and do some settings
* save and re-open, test if anything works well

To me atm it seems there's a problem with different versions and backwards compatibility.

**Comment by VinceLewis** [comment]
Okay, I will try that. Alas I will be away from my beloved music tinkering
till the weekend, doing my day job, so it will be a few days before I can
test this approach.
Sorry for the delay this will cause.

**Comment by boomshop** [comment]
No problem at all, we're sorry for the issues you have with Calf.

**Comment by VinceLewis** [comment]
resolved. Sorry for insane delay.
