### ISSUE TITLE
calf gate-git sound bad.

### ISSUE THREAD

**Issue by XzuRukneg** [calf-studio-gear/calf#81]
I've tested tested calf gate from git (kx studio repo). It works but sound bad: the audio level is diminished.
No problem with stable version with same preset.
Is reports about -git helpful?

**Comment by boomshop** [comment]
Does this github repo come up with the same problems? Cause we're not responsible for the KX builds.

**Comment by XzuRukneg** [comment]
When I said "calf gate from git (kx studio repo)", that mean calf git version from kx special package, called "calf-git". So, it's the same version, yes.

**Comment by boomshop** [comment]
Could you please send in the preset and at best an audio example? And what happens with bypass enabled?

**Comment by jrigg** [comment]
I notice the KXstudio web page points to a dead link for the calf-git source code. How often does KXstudio build from current calf github source? 

Gate from this github repo is working fine here in both calfjackhost and LV2/jalv.gtk (on Debian 8 amd64) but I don't know what preset the OP is using.

**Comment by boomshop** [comment]
> I notice the KXstudio web page points to a dead link for the calf-git source code. How often does KXstudio build from current calf github source? 

I have no clue.

@XzuRukneg : Seems you need to make sure that you problem exists with the build of this repository.

**Comment by XzuRukneg** [comment]
Ok. Sorry for delay I'm preoccupied by other things now. If you don't got issue, probably mines comes from my specific version. I'll test with a own -git build later to confirm.

**Comment by boomshop** [comment]
No more activity for 18 months, so closing. Please re-open if this is still an issue.
