### ISSUE TITLE
Segfault when trying to activate calf-reverb in guitarix

### ISSUE THREAD

**Issue by trebmuh** [calf-studio-gear/calf#91]
Using an up-to-date debian jessie + guitarix 0.34 + calf from git 72b13fa:
- start guitarix
- Ctrl + U
- select "LV2 only"
- search for "calf reverb"
- tick its box
- click "Apply"
- click "Save"
- (back in the main windows) click on : _guitarix's menu -> Plugins ->  Stereo plugins -> External -> Calf reverb_
- (it appears in the rack)
- click on its left on the on/off button to try activate it

...bang, segfault

I tried with:
- guitarix 0.31 + calf from git 72b13fa, same behavior.
- guitarix 0.34 + calf 0.0.60, it works.

So to me, it sounds like it something on the calf side which happened between 0.0.60 and now.
Let me know if I can do something to help you (testing a patch or whatever).

Hope that helps

**Comment by YruamaLairba** [comment]
same problem with guitarix 0.35.1 + calf from git 72b13fa, same behavior.

**Comment by trebmuh** [comment]
So.. I found a strange workardound: I just removed the ~/.config/guitarix/ folder and know, it works as expected, no more segfault... So I'm a bit puzzled about what's going on here and I'm not sure that it belongs, as an issue, to calf or to guitarix.
Any advice welcome.

**Comment by jrigg** [comment]
That sounds to me like guitarix was trying to load the calf plugin with some parameter (preset?) which is no longer appropriate. Did you keep a copy of the old guitarix config file?

**Comment by trebmuh** [comment]
@jrigg : not me unfortunately, but maybe @YruamaLairba did. YL, did you?

**Comment by YruamaLairba** [comment]
i think i found the problem. When a plugin is enabled, guitarix seems to create  a file  in "$HOME/.config/guitarix/plugins/" that describe the plugin. So, when the calf plugins are updated this description can become wrong and we obtain a crash when activating the corresponding plugin.

the only way a found to solve this is to disable the plugin, delete the file, and re-enable the plugin

I join the file generated with an old version of calf reverb, just extract it and put it in "$HOME/.config/guitarix/plugins/".

[http%3a%2f%2fcalf%2esourceforge%2enet%2fplugins%2fReverb.js.zip](https://github.com/calf-studio-gear/calf/files/418517/http.3a.2f.2fcalf.2esourceforge.2enet.2fplugins.2fReverb.js.zip)

**Comment by boomshop** [comment]
Closed since there's not much we can do about it atm.
