### ISSUE TITLE
Calf Saturator mix knob cancel out high frequencies.

### ISSUE THREAD

**Issue by 38github** [calf-studio-gear/calf#92]
Calf Saturator mix knob cancel out high frequencies.

**Comment by boomshop** [comment]
So you hear a difference when toggling bypass while mix is at 0%?

**Comment by 38github** [comment]
No, but is around ~50%.

**Comment by boomshop** [comment]
mix at 0% means no saturation is added (like bypass activated), mix at 100% means no clean signal. So what you mean by "canceled out" is the harmonics Saturator produces which means everything works like expected.

**Comment by 38github** [comment]
If you listen to a source with high frequencies at 0% and 100% you will hear the highest frequencies that the incoming audio has but at 50% they disappear/attenuate.

**Comment by jrigg** [comment]
If odd harmonics are generated using a power function (eg. cube for third harmonic) some fundamental frequency is generated too. If that's in reverse phase to the original signal some attenuation will be apparent. Could a distortion polarity switch be a solution?

**Comment by jrigg** [comment]
You can see the effect in a spectrum analyser with a white noise input to the plugin. At 0% the noise spectrum is flat, at 100% there's low pass filtering with -3db around 17kHz (regardless of tone setting). At 50% mix there's a 25dB notch at around 12.5kHz. 

Those figures are at the default saturation setting. The notch gets deeper as saturation is decreased, so there's definitely something wrong.

**Comment by jrigg** [comment]
The Exciter also has notches in the response. At the default setting there's a 20dB notch at 10kHz. The frequency of the notch moves up and down with the Scope frequency when that is adjusted.
Engaging the Ceiling filter produces a second notch at a higher frequency.

**Comment by 38github** [comment]
How is it going with finding the problem causing this? Regards.

**Comment by boomshop** [comment]
No progress by now and it seems that it will take a while if no one else steps in.

**Comment by jrigg** [comment]
The LP filter looks like it might be intended to reduce alias products, but putting it after the saturation stage will do nothing to reduce in-band alias products. It could probably be removed, thus removing a potential delay. I'm not familiar enough with the code (and I don't have enough time right now to study it) to try it myself.

**Comment by unfa** [comment]
I also recently hear this problem. 50% of saturation seems to cancel out the highs, while 0% or 100% doesn't do that. I guess there must be a phasing issue going on.

**Comment by 38github** [comment]
Has this been resolved in upcoming version? Regards.

**Comment by boomshop** [comment]
The close notification links to the corresponding commit. 0.90.0 comes with the fix included. Solution is to have toggles to activate the filters (then the cancellation happens again due to the filter design).
