### ISSUE TITLE
Added Calf Compressor adds annoying 6dB output on the get go.

### ISSUE THREAD

**Issue by 38github** [calf-studio-gear/calf#93]
Added Calf Compressor adds annoying 6dB output on the get go. Would like to see it having unity volume when added.

**Comment by 38github** [comment]
Any chance hearing why this is not something to "fix"?

**Comment by boomshop** [comment]
It's not a bug but a preset. If you add Compressor to a quite normalized track (e.g. vocals) with the default ratio and threshold 6dB is an average makeup after default compression.

**Comment by unfa** [comment]
I think I agree that the 6 dB of gain is a lot and I usually get a rapid loudness jump when I ass a Calf Compressor to my effect chain - Maybe I usually operate on much quieter tracks so the threshold is too high for the makeup to have an expected result.

I think this might be worth putting up a poll among users.

**Comment by boomshop** [comment]
e2ff9eba6bee

**Comment by unfa** [comment]
Wow, that was quick :D Thanks!
