### ISSUE TITLE
Compilation without cairo fails

### ISSUE THREAD

**Issue by david0** [calf-studio-gear/calf#95]
The compilation of calf plugin (without GTK gui) without an installed version of cairo fails:

```
[...]
    Calf configured

    Debug mode:                  no
    With SSE:                    no
    Experimental plugins:        yes
    Common GUI code:             no (GTK+ 2.12 and cairo 1.2 or newer required)
    LV2 enabled:                 yes
    LV2 GTK+ GUI enabled:        no
    JACK host enabled:           no
    LASH enabled:                no
    Old-style JACK MIDI:         no

    Installation prefix:         /usr/local/Cellar/calf/72b13fa8670738e735184494554a9d6f3fad56ac
[...]
analyzer.cpp:21:10: fatal error: 'cairo/cairo.h' file not found
#include <cairo/cairo.h>
```

Full log under https://gist.github.com/david0/6b73867e124c6e746a8c5485572eece9

**Comment by boomshop** [comment]
Could you please test once more? Thanks in advance.

**Comment by david0** [comment]
Nope, basically the same error: https://gist.githubusercontent.com/david0/6b73867e124c6e746a8c5485572eece9/raw/86f7bbda22eb9997d02e1923e374eac5189e4305/gistfile1.txt

**Comment by kfoltman** [comment]
It should be fixed now. Please check and let us know if it's working.

**Comment by david0** [comment]
Now it works, thanks!
